#-- Copyright 2022 Google LLC
#--
#-- Licensed under the Apache License, Version 2.0 (the "License");
#-- you may not use this file except in compliance with the License.
#-- You may obtain a copy of the License at
#--
#--     https://www.apache.org/licenses/LICENSE-2.0
#--
#-- Unless required by applicable law or agreed to in writing, software
#-- distributed under the License is distributed on an "AS IS" BASIS,
#-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#-- See the License for the specific language governing permissions and
#-- limitations under the License.
CREATE OR REPLACE VIEW `{{ project_id_tgt }}.{{ dataset_reporting_tgt }}.CustomerClearedItems_BSAD`
OPTIONS(
  description = "Finance Accounting Customer Cleared Items"
)
AS
<<<<<<< HEAD
--##S4## 
--##S4## SELECT 
--##S4## MANDT AS Client_MANDT, BUKRS AS CompanyCode_BUKRS, BELNR AS AccountingDocumentNumber_BELNR, GJAHR AS FiscalYear_GJAHR,
--##S4## BUZEI AS NumberOfLineItemWithinAccountingDocument_BUZEI, BUZID AS IdentificationOfTheLineItem_BUZID,
--##S4## AUGDT AS ClearingDate_AUGDT, AUGCP AS ClearingEntryDate_AUGCP, AUGBL AS DocumentNumberOfTheClearingDocument_AUGBL,
--##S4## BSCHL AS Posting_BSCHL, KOART AS AccountType_KOART, UMSKZ AS SpecialGlIndicator_UMSKZ,
--##S4## UMSKS AS SpecialGlTransactionType_UMSKS, 
--##S4## BLART AS DocumentType_BLART, BLDAT AS DocumentDateInDocument_BLDAT, BUDAT AS PostingDateInTheDocument_BUDAT,
--##S4## MONAT AS FiscalPeriod_MONAT, CPUDT AS DayOnWhichAccountingDocumentWasEntered_CPUDT, CPUTM AS TimeOfEntry_CPUTM,
--##S4## AEDAT AS DateOfTheLastDocumentChangeByTransaction_AEDAT, UPDDT AS DateOfTheLastDocumentUpdate_UPDDT,
--##S4## WWERT AS TranslationDate_WWERT, USNAM AS UserName_USNAM, TCODE AS TransactionCode_TCODE,
--##S4## BVORG AS NumberOfACrossCompanyCodePostingTransaction_BVORG, XBLNR AS ReferenceDocumentNumber_XBLNR,
--##S4## DBBLG AS RecurringEntryDocumentNumber_DBBLG, STBLG AS ReverseDocumentNumber_STBLG, STJAH AS ReverseDocumentFiscalYear_STJAH,
--##S4## BKTXT AS DocumentHeaderText_BKTXT, WAERS AS Currency_WAERS, KURSF AS ExchangeRate_KURSF,
--##S4## KZWRS AS CurrencyForTheGroupCurrency_KZWRS, KZKRS AS GroupCurrencyExchangeRate_KZKRS, BSTAT AS DocumentStatus_BSTAT,
--##S4## XNETB AS Indicator_DocumentPostedNet_XNETB, FRATH AS UnplannedDeliveryCosts_FRATH,
--##S4## XRUEB AS Indicator_DocumentIsPostedToAPreviousPeriod_XRUEB, GLVOR AS BusinessTransaction_GLVOR,
--##S4## GRPID AS BatchInputSessionName_GRPID, DOKID AS DocumentNameInTheArchiveSystem_DOKID, ARCID AS ExtractIdDocumentHeader_ARCID,
--##S4## IBLAR AS InternalDocumentTypeForDocumentControl_IBLAR, AW AS Object_AW,
--##S4## FIKRS AS FinancialManagementArea_FIKRS, HWAER AS LocalCurrency_HWAER, HWAE2 AS CurrencyOfSecondLocalCurrency_HWAE2,
--##S4## HWAE3 AS CurrencyOfThirdLocalCurrency_HWAE3, KURS2 AS ExchangeRateForTheSecondLocalCurrency_KURS2,
--##S4## KURS3 AS ExchangeRateForTheThirdLocalCurrency_KURS3, BASW2 AS SourceCurrencyForCurrencyTranslation_BASW2,
--##S4## BASW3 AS SourceCurrencyForCurrencyTranslation_BASW3, UMRD2 AS TranslationDateTypeForSecondLocalCurrency_UMRD2,
--##S4## UMRD3 AS TranslationDateTypeForThirdLocalCurrency_UMRD3, XSTOV AS Indicator_DocumentIsFlaggedForReversal_XSTOV,
--##S4## STODT AS PlannedDateForTheReversePosting_STODT, XMWST AS CalculateTaxAutomatically_XMWST,
--##S4## CURT2 AS CurrencyTypeOfSecondLocalCurrency_CURT2, CURT3 AS CurrencyTypeOfThirdLocalCurrency_CURT3,
--##S4## KUTY2 AS ExchangeRateType_KUTY2, KUTY3 AS ExchangeRateType_KUTY3, XSNET AS GlAccountAmountsEnteredExcludeTax_XSNET,
--##S4## AUSBK AS SourceCompanyCode_AUSBK, DUEFL AS StatusOfDataTransferIntoSubsequentRelease_DUEFL, AWSYS AS LogicalSystem_AWSYS, TXKRS AS ExchangeRateForTaxes_TXKRS,
--##S4## CTXKRS AS RateForTaxValuesInLocalCurrency__plantsAbroad___CTXKRS, LOTKZ AS LotNumberForRequests_LOTKZ, 
--##S4## XWVOF AS Indicator_CustomerBillOfExchangePaymentBeforeDueDate_XWVOF, STGRD AS ReasonForReversal_STGRD,
--##S4## PPNAM AS NameOfUserWhoParkedThisDocument_PPNAM, BRNCH AS BranchNumber_BRNCH, NUMPG AS NumberOfPagesOfInvoice_NUMPG,
--##S4## ADISC AS Indicator_EntryRepresentsADiscountDocument_ADISC, XREF1_HD AS Reference1InternalForDocumentHeader_XREF1_HD,
--##S4## XREF2_HD AS Reference2InternalForDocumentHeader_XREF2_HD, XREVERSAL AS SpecifiesWhetherDocIsReversalDocOrReversedDoc_XREVERSAL,
--##S4## REINDAT AS InvoiceReceiptDate_REINDAT, RLDNR AS LedgerInGeneralLedgerAccounting_RLDNR, LDGRP AS LedgerGroup_LDGRP,
--##S4## PROPMANO AS RealEstateManagementMandate_PROPMANO, XBLNR_ALT AS AlternativeReferenceNumber_XBLNR_ALT,
--##S4## VATDATE AS TaxReportingDate_VATDATE, DOCCAT AS ClassificationOfAnFiDocument_DOCCAT,
--##S4## XSPLIT AS FiDocumentOriginatesFromSplitPosting__indicator___XSPLIT, CASH_ALLOC AS CashRelevantDocument_CASH_ALLOC,
--##S4## FOLLOW_ON AS FollowOnDocumentIndicator_FOLLOW_ON, XREORG AS DocContainsOpenItemThatWasTransferredDuringReorg_XREORG,
--##S4## SUBSET AS DefinesSubsetOfComponentsForTheFicoInterface_SUBSET, KURST AS ExchangeRateType_KURST,
--##S4## KURSX AS MarketDataExchangeRate_KURSX, KUR2X AS MarketDataExchangeRate2_KUR2X, KUR3X AS MarketDataExchangeRate3_KUR3X,
--##S4## XMCA AS DocumentOriginatesFromMultiCurrencyAccounting_XMCA, RESUBMISSION AS DateOfResubmission_RESUBMISSION,
--##S4## PSOTY AS DocumentCategoryPaymentRequests_PSOTY, PSOAK AS Reason_PSOAK,
--##S4## PSOKS AS Region_PSOKS, PSOSG AS ReasonForReversalIsPsRequests_PSOSG, PSOFN AS IsPs_FileNumber_PSOFN,
--##S4## INTFORM AS InterestFormula_INTFORM, INTDATE AS InterestCalcDate_INTDATE, PSOBT AS PostingDay_PSOBT,
--##S4## PSOZL AS ActualPosting_PSOZL, PSODT AS DateOfLastChange_PSODT, PSOTM AS LastChangedAt_PSOTM,
--##S4## FM_UMART AS TypeOfPaymentTransfer_FM_UMART, CCINS AS PaymentCards_CardType_CCINS, CCNUM AS PaymentCards_CardNumber_CCNUM,
--##S4## SSBLK AS PaymentStatisticalSamplingBlock_SSBLK, BATCH AS LotNumberForDocuments_BATCH, SNAME AS UserName_SNAME,
--##S4## SAMPLED AS SampledInvoiceByPaymentCertification_SAMPLED, EXCLUDE_FLAG AS PpaExcludeIndicator_EXCLUDE_FLAG,
--##S4## BLIND AS BudgetaryLedgerIndicator_BLIND, OFFSET_STATUS AS TreasuryOffsetStatus_OFFSET_STATUS,
--##S4## OFFSET_REFER_DAT AS DateRecordReferredToTreasury_OFFSET_REFER_DAT, PENRC AS ReasonForLatePayment_PENRC,
--##S4## KNUMV AS NumberOfTheDocumentCondition_KNUMV,
--##S4## ZUMSK AS TargetSpecialGlIndicator_ZUMSK, 
--##S4## GSBER AS BusinessArea_GSBER, PARGB AS TradingPartnerBusinessArea_PARGB, MWSKZ AS TaxOnSalespurchasesCode_MWSKZ,
--##S4## QSSKZ AS WithholdingTaxCode_QSSKZ, 
--##S4## CASE
--##S4## WHEN bseg.shkzg = 'S' THEN bseg.wrbtr  -- S = Debit | Amount in document currency
--##S4## WHEN bseg.shkzg = 'H' THEN bseg.wrbtr * -1  -- H = Credit | Amount in document currency
--##S4## ELSE bseg.wrbtr
--##S4## END AS AmountInDocumentCurrency_bseg.wrbtr,
--##S4## CASE
--##S4## WHEN bseg.shkzg = 'S' THEN bseg.dmbtr  -- S = Debit | Amount in document currency
--##S4## WHEN bseg.shkzg = 'H' THEN bseg.dmbtr * -1  -- H = Credit | Amount in document currency
--##S4## ELSE bseg.dmbtr
--##S4## END AS AmountInLocalCurrency_bseg.dmbtr, 
--##S4## KZBTR AS OriginalReductionAmountInLocalCurrency_KZBTR, PSWBT AS AmountForUpdatingInGeneralLedger_PSWBT,
--##S4## PSWSL AS UpdateCurrencyForGeneralLedgerTransactionFigures_PSWSL, TXBHW AS OriginalTaxBaseAmountInLocalCurrency_TXBHW,
--##S4## TXBFW AS OriginalTaxBaseAmountInDocumentCurrency_TXBFW, MWSTS AS TaxAmountInLocalCurrency_MWSTS,
--##S4## WMWST AS TaxAmountInDocumentCurrency_WMWST, HWBAS AS TaxBaseAmountInLocalCurrency_HWBAS,
--##S4## FWBAS AS TaxBaseAmountInDocumentCurrency_FWBAS, HWZUZ AS ProvisionAmountInLocalCurrency_HWZUZ,
--##S4## FWZUZ AS AdditionalTaxInDocumentCurrency_FWZUZ, SHZUZ AS DebitcreditAdditionForCashDiscount_SHZUZ,
--##S4## STEKZ AS VersionNumberComponent_STEKZ, MWART AS TaxType_MWART, TXGRP AS GroupIndicatorForTaxLineItems_TXGRP,
--##S4## KTOSL AS Transaction_KTOSL, QSSHB AS WithholdingTaxBaseAmount_QSSHB, KURSR AS HedgedExchangeRate_KURSR,
--##S4## GBETR AS HedgedAmountInForeignCurrency_GBETR, BDIFF AS ValuationDifference_BDIFF,
--##S4## BDIF2 AS ValuationDifferenceForTheSecondLocalCurrency_BDIF2, VALUT AS ValueDate_VALUT, ZUONR AS AssignmentNumber_ZUONR,
--##S4## SGTXT AS ItemText_SGTXT, ZINKZ AS ExemptedFromInterestCalculation_ZINKZ, VBUND AS CompanyIdOfTradingPartner_VBUND,
--##S4## BEWAR AS TransactionType_BEWAR, ALTKT AS GroupAccountNumber_ALTKT, VORGN AS TransactionTypeForGeneralLedger_VORGN,
--##S4## FDLEV AS PlanningLevel_FDLEV, FDGRP AS PlanningGroup_FDGRP, FDWBT AS PlannedAmountInDocumentOrGlAccountCurrency_FDWBT,
--##S4## FDTAG AS PlanningDate_FDTAG, FKONT AS FinancialBudgetItem_FKONT, KOKRS AS ControllingArea_KOKRS,
--##S4## KOSTL AS CostCenter_KOSTL, PROJN AS Old_ProjectNumberPs_posnr_PROJN, AUFNR AS OrderNumber_AUFNR,
--##S4## VBELN AS BillingDocument_VBELN, VBEL2 AS SalesDocument_VBEL2, POSN2 AS SalesDocumentItem_POSN2,
--##S4## ETEN2 AS ScheduleLineNumber_ETEN2, ANLN1 AS MainAssetNumber_ANLN1, ANLN2 AS AssetSubnumber_ANLN2,
--##S4## ANBWA AS AssetTransactionType_ANBWA, BZDAT AS AssetValueDate_BZDAT, PERNR AS PersonnelNumber_PERNR,
--##S4## XUMSW AS Indicator_SalesRelatedItem_XUMSW, XHRES AS Indicator_ResidentGlAccount_XHRES,
--##S4## XKRES AS Indicator_CanLineItemsBeDisplayedByAccount_XKRES, XOPVW AS Indicator_OpenItemManagement_XOPVW,
--##S4## XCPDD AS Indicator_AddressAndBankDataSetIndividually_XCPDD, XSKST AS Indicator_StatisticalPostingToCostCenter_XSKST,
--##S4## XSAUF AS Indicator_PostingToOrderIsStatistical_XSAUF, XSPRO AS Indicator_PostingToProjectIsStatistical_XSPRO,
--##S4## XSERG AS Indicator_PostingToProfitabilityAnalysisIsStatistical_XSERG, XFAKT AS Indicator_BillingDocumentUpdateSuccessful_XFAKT,
--##S4## XUMAN AS Indicator_TransferPostingFromDownPayment_XUMAN, XANET AS Indicator_DownPaymentInNetProcedure_XANET,
--##S4## XSKRL AS Indicator_LineItemNotLiableToCashDiscount_XSKRL, XINVE AS Indicator_CapitalGoodsAffected_XINVE,
--##S4## XPANZ AS DisplayItem_XPANZ, XAUTO AS Indicator_LineItemAutomaticallyCreated_XAUTO, XNCOP AS Indicator_ItemsCannotBeCopied_XNCOP,
--##S4## XZAHL AS Indicator_IsPostingUsedInAPaymentTransaction_XZAHL, SAKNR AS GlAccountNumber_SAKNR,
--##S4## HKONT AS GeneralLedgerAccount_HKONT, KUNNR AS CustomerNumber_KUNNR, LIFNR AS AccountNumberOfVendorOrCreditor_LIFNR,
--##S4## FILKD AS AccountNumberOfTheBranch_FILKD, XBILK AS Indicator_AccountIsABalanceSheetAccount_XBILK,
--##S4## GVTYP AS PLStatementAccountType_GVTYP, HZUON AS AssignmentNumberForSpecialGlAccounts_HZUON,
--##S4## ZFBDT AS BaselineDateForDueDateCalculation_ZFBDT, ZTERM AS TermsOfPayment_ZTERM, ZBD1T AS CashDiscountDays1_ZBD1T,
--##S4## ZBD2T AS CashDiscountDays2_ZBD2T, ZBD3T AS NetPaymentTermsPeriod_ZBD3T, ZBD1P AS CashDiscountPercentage1_ZBD1P,
--##S4## ZBD2P AS CashDiscountPercentage2_ZBD2P, SKFBT AS AmountEligibleForCashDiscountInDocumentCurrency_SKFBT,
--##S4## SKNTO AS CashDiscountAmountInLocalCurrency_SKNTO, WSKTO AS CashDiscountAmountInDocumentCurrency_WSKTO,
--##S4## ZLSCH AS PaymentMethod_ZLSCH, ZLSPR AS PaymentBlock_ZLSPR, ZBFIX AS FixedPaymentTerms_ZBFIX,
--##S4## HBKID AS ShortForAHouseBank_HBKID, BVTYP AS PartnerBankType_BVTYP, NEBTR AS NetPaymentAmount_NEBTR,
--##S4## MWSK1 AS TaxCodeForDistribution_MWSK1, DMBT1 AS AmountInLocalCurrencyForTaxDistribution_DMBT1,
--##S4## WRBT1 AS AmountInForeignCurrencyForTaxBreakdown_WRBT1, MWSK2 AS TaxCodeForDistribution_MWSK2,
--##S4## DMBT2 AS AmountInLocalCurrencyForTaxDistribution_DMBT2, WRBT2 AS AmountInForeignCurrencyForTaxBreakdown_WRBT2,
--##S4## MWSK3 AS TaxCodeForDistribution_MWSK3, DMBT3 AS AmountInLocalCurrencyForTaxDistribution_DMBT3,
--##S4## WRBT3 AS AmountInForeignCurrencyForTaxBreakdown_WRBT3, REBZG AS DocumentNoOfTheInvoiceToWhichTheTransactionBelongs_REBZG,
--##S4## REBZJ AS FiscalYearOfTheRelevantInvoice__forCreditMemo___REBZJ, REBZZ AS LineItemInTheRelevantInvoice_REBZZ,
--##S4## REBZT AS FollowOnDocumentType_REBZT, ZOLLT AS CustomsTariffNumber_ZOLLT, ZOLLD AS CustomsDate_ZOLLD,
--##S4## LZBKZ AS StateCentralBankIndicator_LZBKZ, LANDL AS SupplyingCountry_LANDL, DIEKZ AS ServiceIndicator__foreignPayment___DIEKZ,
--##S4## SAMNR AS InvoiceListNumber_SAMNR, ABPER AS SettlementPeriod_ABPER, VRSKZ AS InsuranceIndicator_VRSKZ,
--##S4## VRSDT AS InsuranceDate_VRSDT, DISBN AS NumberOfBillOfExchangeUsageDocument__discountDoc___DISBN,
--##S4## DISBJ AS FiscalYearOfBillOfExchangeUsageDocument_DISBJ, DISBZ AS LineItemWithinTheBillOfExchangeUsageDocument_DISBZ,
--##S4## WVERW AS BillOfExchangeUsageType_WVERW, ANFBN AS DocumentNumberOfTheBillOfExchangePaymentRequest_ANFBN,
--##S4## ANFBJ AS FiscalYearOfTheBillOfExchangePaymentRequestDocument_ANFBJ, ANFBU AS CompanyCodeInWhichBillOfExchPaymentRequestIsPosted_ANFBU,
--##S4## ANFAE AS BillOfExchangePaymentRequestDueDate_ANFAE, BLNBT AS BaseAmountForDeterminingThePreferenceAmount_BLNBT,
--##S4## BLNKZ AS SubsidyIndicatorForDeterminingTheReductionRates_BLNKZ, BLNPZ AS PreferencePercentageRate_BLNPZ,
--##S4## MSCHL AS Dunning_MSCHL, MANSP AS DunningBlock_MANSP, MADAT AS DateOfLastDunningNotice_MADAT,
--##S4## MANST AS DunningLevel_MANST, MABER AS DunningArea_MABER, ESRNR AS PorSubscriberNumber_ESRNR,
--##S4## ESRRE AS PorReferenceNumber_ESRRE, ESRPZ AS PorCheckDigit_ESRPZ, KLIBT AS CreditControlAmount_KLIBT,
--##S4## QSZNR AS CertificateNumberOfTheWithholdingTaxExemption_QSZNR, QBSHB AS WithholdingTaxAmount__inDocumentCurrency___QBSHB,
--##S4## QSFBT AS WithholdingTaxExemptAmount__inDocumentCurrency___QSFBT, NAVHW AS NonDeductibleInputTax__inLocalCurrency___NAVHW,
--##S4## NAVFW AS NonDeductibleInputTax__inDocumentCurrency___NAVFW, MATNR AS MaterialNumber_MATNR, WERKS AS Plant_WERKS,
--##S4## MENGE AS Quantity_MENGE, MEINS AS BaseUnitOfMeasure_MEINS, ERFMG AS QuantityInUnitOfEntry_ERFMG,
--##S4## ERFME AS UnitOfEntry_ERFME, BPMNG AS QuantityInPurchaseOrderPriceUnit_BPMNG, BPRME AS OrderPriceUnit__purchasing___BPRME,
--##S4## EBELN AS PurchasingDocumentNumber_EBELN, EBELP AS ItemNumberOfPurchasingDocument_EBELP,
--##S4## ZEKKN AS SequentialNumberOfAccountAssignment_ZEKKN, ELIKZ AS DeliveryCompletedIndicator_ELIKZ,
--##S4## VPRSV AS PriceControlIndicator_VPRSV, PEINH AS PriceUnit_PEINH, BW AS ValuationArea_BW,
--##S4## BWTAR AS ValuationType_BWTAR, BUSTW AS PostingStringForValues_BUSTW, REWRT AS InvoiceValueEntered__inLocalCurrency___REWRT,
--##S4## REWWR AS InvoiceValueInForeignCurrency_REWWR, BONFB AS AmountQualifyingForBonusInLocalCurrency_BONFB,
--##S4## BUALT AS AmountPostedInAlternativePriceControl_BUALT, PSALT AS AlternativePriceControl_PSALT, NPREI AS NewPrice_NPREI,
--##S4## TBTKZ AS Indicator_SubsequentDebitcredit_TBTKZ, SPGRP AS BlockingReason_Price_SPGRP, SPGRM AS BlockingReason_Quantity_SPGRM,
--##S4## SPGRT AS BlockingReason_Date_SPGRT, SPGRG AS BlockingReason_OrderPriceQuantity_SPGRG,
--##S4## SPGRV AS BlockingReason_ProjectBudget_SPGRV, SPGRQ AS ManualBlockingReason_SPGRQ, STCEG AS VatRegistrationNumber_STCEG,
--##S4## EGBLD AS CountryOfDestinationForDeliveryOfGoods_EGBLD, EGLLD AS SupplyingCountryForDeliveryOfGoods_EGLLD,
--##S4## RSTGR AS ReasonCodeForPayments_RSTGR, RYACQ AS YearOfAcquisition_RYACQ, RPACQ AS PeriodOfAcquisition_RPACQ,
--##S4## RDIFF AS ExchangeRateGainlossRealized_RDIFF, RDIF2 AS ExchangeRateDifferenceRealizedForSecondLocalCurrency_RDIF2,
--##S4## PRCTR AS ProfitCenter_PRCTR, XHKOM AS Indicator_GlAccountAssignedManually_XHKOM, VNAME AS JointVenture_VNAME,
--##S4## RECID AS RecoveryIndicator_RECID, EGRUP AS EquityGroup_EGRUP, VPTNR AS PartnerAccountNumber_VPTNR,
--##S4## VERTT AS ContractType_VERTT, VERTN AS ContractNumber_VERTN, VBEWA AS FlowType_VBEWA, DEPOT AS SecuritiesAccount_DEPOT,
--##S4## TXJCD AS TaxJurisdiction_TXJCD, IM AS InternalForRealEstateObject_IM, DABRZ AS ReferenceDateForSettlement_DABRZ,
--##S4## POPTS AS RealEstateOptionRate_POPTS, FIPOS AS CommitmentItem_FIPOS, KSTRG AS CostObject_KSTRG,
--##S4## NPLNR AS NetworkNumberForAccountAssignment_NPLNR, AUFPL AS TaskListNumberForOperationsInOrder_AUFPL,
--##S4## APLZL AS GeneralCounterForOrder_APLZL, PROJK AS WorkBreakdownStructureElement__wbsElement___PROJK,
--##S4## PAOBJNR AS ProfitabilitySegmentNumber__coPa___PAOBJNR, PASUBNR AS ProfitabilitySegmentChanges__coPa___PASUBNR,
--##S4## SPGRS AS BlockingReason_ItemAmount_SPGRS, SPGRC AS BlockingReason_Quality_SPGRC, BTYPE AS PayrollType_BTYPE,
--##S4## ETYPE AS EquityType_ETYPE, XEGDR AS Indicator_TriangularDealWithinTheEu_XEGDR,
--##S4## LNRAN AS SequenceNumberOfAssetLineItemsInFiscalYear_LNRAN, HRKFT AS OriginGroupAsSubdivisionOfCostElement_HRKFT,
--##S4## DMBE2 AS AmountInSecondLocalCurrency_DMBE2, DMBE3 AS AmountInThirdLocalCurrency_DMBE3,
--##S4## DMB21 AS AmountInSecondLocalCurrencyForTaxBreakdown_DMB21, DMB22 AS AmountInSecondLocalCurrencyForTaxBreakdown_DMB22,
--##S4## DMB23 AS AmountInSecondLocalCurrencyForTaxBreakdown_DMB23, DMB31 AS AmountInThirdLocalCurrencyForTaxBreakdown_DMB31,
--##S4## DMB32 AS AmountInThirdLocalCurrencyForTaxBreakdown_DMB32, DMB33 AS AmountInThirdLocalCurrencyForTaxBreakdown_DMB33,
--##S4## MWST2 AS TaxAmountInSecondLocalCurrency_MWST2, MWST3 AS TaxAmountInThirdLocalCurrency_MWST3,
--##S4## NAVH2 AS NonDeductibleInputTaxInSecondLocalCurrency_NAVH2, NAVH3 AS NonDeductibleInputTaxInThirdLocalCurrency_NAVH3,
--##S4## SKNT2 AS CashDiscountAmountInSecondLocalCurrency_SKNT2, SKNT3 AS CashDiscountAmountInThirdLocalCurrency_SKNT3,
--##S4## BDIF3 AS ValuationDifferenceForTheThirdLocalCurrency_BDIF3, RDIF3 AS ExchangeRateDifferenceRealizedForThirdLocalCurrency_RDIF3,
--##S4## HWMET AS MethodWithWhichTheLocalCurrencyAmountWasDetermined_HWMET, GLUPM AS UpdateMethodForFmFiCaIntegration_GLUPM,
--##S4## XRAGL AS Indicator_ClearingWasReversed_XRAGL, UZAWE AS PaymentMethodSupplement_UZAWE,
--##S4## LOKKT AS AlternativeAccountNumberInCompanyCode_LOKKT, FISTL AS FundsCenter_FISTL, GEBER AS Fund_GEBER,
--##S4## STBUK AS TaxCompanyCode_STBUK, TXBH2 AS TaxBaseoriginalTaxBaseInSecondLocalCurrency_TXBH2,
--##S4## TXBH3 AS TaxBaseoriginalTaxBaseInThirdLocalCurrency_TXBH3, PPRCT AS PartnerProfitCenter_PPRCT,
--##S4## XREF1 AS BusinessPartnerReference_XREF1, XREF2 AS BusinessPartnerReference_XREF2,
--##S4## KBLNR AS DocumentNumberForEarmarkedFunds_KBLNR, KBLPOS AS EarmarkedFunds_DocumentItem_KBLPOS,
--##S4## STTAX AS TaxAmountAsStatisticalInformationInDocumentCurrency_STTAX, FKBER AS FunctionalArea_FKBER,
--##S4## OBZEI AS NumberOfLineItemInOriginalDocument_OBZEI, XNEGP AS Indicator_NegativePosting_XNEGP, RFZEI AS PaymentCardItem_RFZEI,
--##S4## CCBTC AS PaymentCards_SettlementRun_CCBTC, KKBER AS CreditControlArea_KKBER, EMPFB AS Payeepayer_EMPFB,
--##S4## XREF3 AS ReferenceForLineItem_XREF3, DTWS1 AS Instruction1_DTWS1, DTWS2 AS Instruction2_DTWS2,
--##S4## DTWS3 AS Instruction3_DTWS3, DTWS4 AS Instruction4_DTWS4, GRICD AS ActivityCodeForGrossIncomeTax_GRICD,
--##S4## GRIRG AS Region_GRIRG, GITYP AS DistributionTypeForEmploymentTax_GITYP,
--##S4## XPYPR AS Indicator_ItemsFromPaymentProgramBlocked_XPYPR, KIDNO AS PaymentReference_KIDNO,
--##S4## ABSBT AS CreditManagement_HedgedAmount_ABSBT, IDXSP AS InflationIndex_IDXSP, LINFV AS LastAdjustmentDate_LINFV,
--##S4## KONTL AS AcctAssignmentStringForIndustrySpecificAcctAssignmnts_KONTL,
--##S4## TXDAT AS DateForDefiningTaxRates_TXDAT, AGZEI AS ClearingItem_AGZEI, PYCUR AS CurrencyForAutomaticPayment_PYCUR,
--##S4## PYAMT AS AmountInPaymentCurrency_PYAMT, BUPLA AS BusinessPlace_BUPLA, SECCO AS SectionCode_SECCO,
--##S4## LSTAR AS ActivityType_LSTAR, CESSION_KZ AS AccountsReceivablePledgingIndicator_CESSION_KZ, PRZNR AS BusinessProcess_PRZNR,
--##S4## PENLC2 AS PenaltyChargeAmountInSecondLocalCurrency_PENLC2, PENLC3 AS PenaltyChargeAmountInThirdLocalCurrency_PENLC3,
--##S4## PENFC AS PenaltyChargeAmountInDocumentCurrency_PENFC, PENDAYS AS NumberOfDaysForPenaltyChargeCalculation_PENDAYS,
--##S4## GRANT_NBR AS Grant_GRANT_NBR, SCTAX AS TaxPortionFiCaLocalCurrency_SCTAX,
--##S4## FKBER_LONG AS FunctionalArea_FKBER_LONG, GMVKZ AS ItemIsInExecution_GMVKZ, SRTYPE AS TypeOfAdditionalReceivable_SRTYPE,
--##S4## INTRENO AS InternalRealEstateMasterDataCode_INTRENO, MEASURE AS FundedProgram_MEASURE,
--##S4## AUGGJ AS FiscalYearOfClearingDocument_AUGGJ, PPA_EX_IND AS PpaExcludeIndicator_PPA_EX_IND,
--##S4## DOCLN AS SixCharacterPostingItemForLedger_DOCLN, SEGMENT AS SegmentForSegmentalReporting_SEGMENT,
--##S4## PSEGMENT AS PartnerSegmentForSegmentalReporting_PSEGMENT, PFKBER AS PartnerFunctionalArea_PFKBER,
--##S4## HKTID AS IdForAccountDetails_HKTID, KSTAR AS CostElement_KSTAR, XLGCLR AS ClearingSpecificToLedgerGroups_XLGCLR,
--##S4## TAXPS AS TaxDocumentItemNumber_TAXPS, PAYS_PROV AS PaymentServiceProvider_PAYS_PROV,
--##S4## PAYS_TRAN AS PaymentReferenceOfPaymentServiceProvider_PAYS_TRAN, MNDID AS UniqueReferenceToMandateForEachPayee_MNDID,
--##S4## XFRGE_BSEG AS PaymentIsReleased_XFRGE_BSEG, SQUAN AS QuantitySign_SQUAN, ZZSPREG AS SpecialRegion_ZZSPREG,
--##S4## ZZBUSPARTN AS BusinessPartner_ZZBUSPARTN, ZZCHAN AS DistributionChannel_ZZCHAN, ZZPRODUCT AS ProductGroup_ZZPRODUCT,
--##S4## ZZLOCA AS City_ZZLOCA, ZZLOB AS BusinessLine_ZZLOB, ZZUSERFLD1 AS Territory_ZZUSERFLD1,
--##S4## ZZUSERFLD2 AS Ownercont_ZZUSERFLD2, ZZUSERFLD3 AS Vein_ZZUSERFLD3, ZZSTATE AS StateprovinceCode_ZZSTATE,
--##S4## ZZREGION AS Location_ZZREGION, RE_BUKRS AS CashLedger_CompanyCodeForExpenserevenue_RE_BUKRS,
--##S4## RE_ACCOUNT AS CashLedger_ExpenseOrRevenueAccount_RE_ACCOUNT, PGEBER AS PartnerFund_PGEBER,
--##S4## PGRANT_NBR AS PartnerGrant_PGRANT_NBR, BUDGET_PD AS Fm_BudgetPeriod_BUDGET_PD, PBUDGET_PD AS Fm_PartnerBudgetPeriod_PBUDGET_PD,
--##S4## J_1TPBUPL AS BranchCode_J_1TPBUPL, PEROP_BEG AS BillingPeriodOfPerformanceStartDate_PEROP_BEG,
--##S4## PEROP_END AS BillingPeriodOfPerformanceEndDate_PEROP_END, FASTPAY AS PpaFastPayIndicator_FASTPAY,
--##S4## IGNR_IVREF AS Fmfg_IgnoreTheInvoiceReferenceDuringFiDocSplitting_IGNR_IVREF,
--##S4## FMFGUS_ AS UnitedStatesFederalGovernmentFields_FMFGUS_, FMXDOCNR AS FmReferenceDocumentNumber_FMXDOCNR,
--##S4## FMXYEAR AS FmReferenceYear_FMXYEAR, FMXDOCLN AS FmReferenceLineItem_FMXDOCLN,
--##S4## FMXZEKKN AS FmReferenceSequenceAccountAssignment_FMXZEKKN, PRODPER AS ProductionMonth__dateToFindPeriodAndYear___PRODPER,     
--##S4##    '  ' AS AccountAssignmentCategoryForIndustrySolution_KONTT,
--##S4##    '                                                  ' AS AcctAssignmentStringForIndustrySpecificAcctAssignmnts_KONTL,
--##S4##    '     '    AS ReferenceProcedure_AWTYP,
--##S4##    '          ' as re_account,
--##S4##    '00000000' as uebgdat,
--##S4##    '          ' as logsystem_sender,
--##S4##    '    '       as bukrs_sender,
--##S4##    '          ' as belnr_sender,
--##S4##    '0000'       as gjahr_sender,
--##S4##    '000'        as buzei_sender,
--##S4##    '          ' as bdgt_account
--##S4##    from kittycorn-staging.2CDC_PROCESSED.bsad_bck where xarch = 'X'
--##S4## UNION ALL
=======

{% if sql_flavour.upper() == 'S4' %} -- noqa: L003
SELECT -- noqa: L003
  MANDT AS Client_MANDT, BUKRS AS CompanyCode_BUKRS, BELNR AS AccountingDocumentNumber_BELNR, GJAHR AS FiscalYear_GJAHR,
  BUZEI AS NumberOfLineItemWithinAccountingDocument_BUZEI, BUZID AS IdentificationOfTheLineItem_BUZID,
  AUGDT AS ClearingDate_AUGDT, AUGCP AS ClearingEntryDate_AUGCP, AUGBL AS DocumentNumberOfTheClearingDocument_AUGBL,
  BSCHL AS Posting_BSCHL, KOART AS AccountType_KOART, UMSKZ AS SpecialGlIndicator_UMSKZ,
  UMSKS AS SpecialGlTransactionType_UMSKS,
  BLART AS DocumentType_BLART, BLDAT AS DocumentDateInDocument_BLDAT, BUDAT AS PostingDateInTheDocument_BUDAT,
  MONAT AS FiscalPeriod_MONAT, CPUDT AS DayOnWhichAccountingDocumentWasEntered_CPUDT, CPUTM AS TimeOfEntry_CPUTM,
  AEDAT AS DateOfTheLastDocumentChangeByTransaction_AEDAT, UPDDT AS DateOfTheLastDocumentUpdate_UPDDT,
  WWERT AS TranslationDate_WWERT, USNAM AS UserName_USNAM, TCODE AS TransactionCode_TCODE,
  BVORG AS NumberOfACrossCompanyCodePostingTransaction_BVORG, XBLNR AS ReferenceDocumentNumber_XBLNR,
  DBBLG AS RecurringEntryDocumentNumber_DBBLG, STBLG AS ReverseDocumentNumber_STBLG, STJAH AS ReverseDocumentFiscalYear_STJAH,
  BKTXT AS DocumentHeaderText_BKTXT, WAERS AS Currency_WAERS, KURSF AS ExchangeRate_KURSF,
  KZWRS AS CurrencyForTheGroupCurrency_KZWRS, KZKRS AS GroupCurrencyExchangeRate_KZKRS, BSTAT AS DocumentStatus_BSTAT,
  XNETB AS Indicator_DocumentPostedNet_XNETB, FRATH AS UnplannedDeliveryCosts_FRATH,
  XRUEB AS Indicator_DocumentIsPostedToAPreviousPeriod_XRUEB, GLVOR AS BusinessTransaction_GLVOR,
  GRPID AS BatchInputSessionName_GRPID, DOKID AS DocumentNameInTheArchiveSystem_DOKID, ARCID AS ExtractIdDocumentHeader_ARCID,
  IBLAR AS InternalDocumentTypeForDocumentControl_IBLAR, AW AS Object_AW,
  FIKRS AS FinancialManagementArea_FIKRS, HWAER AS LocalCurrency_HWAER, HWAE2 AS CurrencyOfSecondLocalCurrency_HWAE2,
  HWAE3 AS CurrencyOfThirdLocalCurrency_HWAE3, KURS2 AS ExchangeRateForTheSecondLocalCurrency_KURS2,
  KURS3 AS ExchangeRateForTheThirdLocalCurrency_KURS3, BASW2 AS SourceCurrencyForCurrencyTranslation_BASW2,
  BASW3 AS SourceCurrencyForCurrencyTranslation_BASW3, UMRD2 AS TranslationDateTypeForSecondLocalCurrency_UMRD2,
  UMRD3 AS TranslationDateTypeForThirdLocalCurrency_UMRD3, XSTOV AS Indicator_DocumentIsFlaggedForReversal_XSTOV,
  STODT AS PlannedDateForTheReversePosting_STODT, XMWST AS CalculateTaxAutomatically_XMWST,
  CURT2 AS CurrencyTypeOfSecondLocalCurrency_CURT2, CURT3 AS CurrencyTypeOfThirdLocalCurrency_CURT3,
  KUTY2 AS ExchangeRateType_KUTY2, KUTY3 AS ExchangeRateType_KUTY3, XSNET AS GlAccountAmountsEnteredExcludeTax_XSNET,
  AUSBK AS SourceCompanyCode_AUSBK, DUEFL AS StatusOfDataTransferIntoSubsequentRelease_DUEFL, AWSYS AS LogicalSystem_AWSYS, TXKRS AS ExchangeRateForTaxes_TXKRS,
  CTXKRS AS RateForTaxValuesInLocalCurrency__plantsAbroad___CTXKRS, LOTKZ AS LotNumberForRequests_LOTKZ,
  XWVOF AS Indicator_CustomerBillOfExchangePaymentBeforeDueDate_XWVOF, STGRD AS ReasonForReversal_STGRD,
  PPNAM AS NameOfUserWhoParkedThisDocument_PPNAM, BRNCH AS BranchNumber_BRNCH, NUMPG AS NumberOfPagesOfInvoice_NUMPG,
  ADISC AS Indicator_EntryRepresentsADiscountDocument_ADISC, XREF1_HD AS Reference1InternalForDocumentHeader_XREF1_HD,
  XREF2_HD AS Reference2InternalForDocumentHeader_XREF2_HD, XREVERSAL AS SpecifiesWhetherDocIsReversalDocOrReversedDoc_XREVERSAL,
  REINDAT AS InvoiceReceiptDate_REINDAT, RLDNR AS LedgerInGeneralLedgerAccounting_RLDNR, LDGRP AS LedgerGroup_LDGRP,
  PROPMANO AS RealEstateManagementMandate_PROPMANO, XBLNR_ALT AS AlternativeReferenceNumber_XBLNR_ALT,
  VATDATE AS TaxReportingDate_VATDATE, DOCCAT AS ClassificationOfAnFiDocument_DOCCAT,
  XSPLIT AS FiDocumentOriginatesFromSplitPosting__indicator___XSPLIT, CASH_ALLOC AS CashRelevantDocument_CASH_ALLOC,
  FOLLOW_ON AS FollowOnDocumentIndicator_FOLLOW_ON, XREORG AS DocContainsOpenItemThatWasTransferredDuringReorg_XREORG,
  SUBSET AS DefinesSubsetOfComponentsForTheFicoInterface_SUBSET, KURST AS ExchangeRateType_KURST,
  KURSX AS MarketDataExchangeRate_KURSX, KUR2X AS MarketDataExchangeRate2_KUR2X, KUR3X AS MarketDataExchangeRate3_KUR3X,
  XMCA AS DocumentOriginatesFromMultiCurrencyAccounting_XMCA, RESUBMISSION AS DateOfResubmission_RESUBMISSION,
  PSOTY AS DocumentCategoryPaymentRequests_PSOTY, PSOAK AS Reason_PSOAK,
  PSOKS AS Region_PSOKS, PSOSG AS ReasonForReversalIsPsRequests_PSOSG, PSOFN AS IsPs_FileNumber_PSOFN,
  INTFORM AS InterestFormula_INTFORM, INTDATE AS InterestCalcDate_INTDATE, PSOBT AS PostingDay_PSOBT,
  PSOZL AS ActualPosting_PSOZL, PSODT AS DateOfLastChange_PSODT, PSOTM AS LastChangedAt_PSOTM,
  FM_UMART AS TypeOfPaymentTransfer_FM_UMART, CCINS AS PaymentCards_CardType_CCINS, CCNUM AS PaymentCards_CardNumber_CCNUM,
  SSBLK AS PaymentStatisticalSamplingBlock_SSBLK, BATCH AS LotNumberForDocuments_BATCH, SNAME AS UserName_SNAME,
  SAMPLED AS SampledInvoiceByPaymentCertification_SAMPLED, EXCLUDE_FLAG AS PpaExcludeIndicator_EXCLUDE_FLAG,
  BLIND AS BudgetaryLedgerIndicator_BLIND, OFFSET_STATUS AS TreasuryOffsetStatus_OFFSET_STATUS,
  OFFSET_REFER_DAT AS DateRecordReferredToTreasury_OFFSET_REFER_DAT, PENRC AS ReasonForLatePayment_PENRC,
  KNUMV AS NumberOfTheDocumentCondition_KNUMV,
  ZUMSK AS TargetSpecialGlIndicator_ZUMSK,
  GSBER AS BusinessArea_GSBER, PARGB AS TradingPartnerBusinessArea_PARGB, MWSKZ AS TaxOnSalespurchasesCode_MWSKZ,
  QSSKZ AS WithholdingTaxCode_QSSKZ,
  CASE
    WHEN bseg.shkzg = 'S' THEN bseg.wrbtr  -- S = Debit | Amount in document currency
    WHEN bseg.shkzg = 'H' THEN bseg.wrbtr * -1  -- H = Credit | Amount in document currency
    ELSE bseg.wrbtr
  END AS AmountInDocumentCurrency_bseg_wrbtr,
  CASE
    WHEN bseg.shkzg = 'S' THEN bseg.dmbtr  -- S = Debit | Amount in document currency
    WHEN bseg.shkzg = 'H' THEN bseg.dmbtr * -1  -- H = Credit | Amount in document currency
    ELSE bseg.dmbtr
  END AS AmountInLocalCurrency_bseg_dmbtr,
  KZBTR AS OriginalReductionAmountInLocalCurrency_KZBTR, PSWBT AS AmountForUpdatingInGeneralLedger_PSWBT,
  PSWSL AS UpdateCurrencyForGeneralLedgerTransactionFigures_PSWSL, TXBHW AS OriginalTaxBaseAmountInLocalCurrency_TXBHW,
  TXBFW AS OriginalTaxBaseAmountInDocumentCurrency_TXBFW, MWSTS AS TaxAmountInLocalCurrency_MWSTS,
  WMWST AS TaxAmountInDocumentCurrency_WMWST, HWBAS AS TaxBaseAmountInLocalCurrency_HWBAS,
  FWBAS AS TaxBaseAmountInDocumentCurrency_FWBAS, HWZUZ AS ProvisionAmountInLocalCurrency_HWZUZ,
  FWZUZ AS AdditionalTaxInDocumentCurrency_FWZUZ, SHZUZ AS DebitcreditAdditionForCashDiscount_SHZUZ,
  STEKZ AS VersionNumberComponent_STEKZ, MWART AS TaxType_MWART, TXGRP AS GroupIndicatorForTaxLineItems_TXGRP,
  KTOSL AS Transaction_KTOSL, QSSHB AS WithholdingTaxBaseAmount_QSSHB, KURSR AS HedgedExchangeRate_KURSR,
  GBETR AS HedgedAmountInForeignCurrency_GBETR, BDIFF AS ValuationDifference_BDIFF,
  BDIF2 AS ValuationDifferenceForTheSecondLocalCurrency_BDIF2, VALUT AS ValueDate_VALUT, ZUONR AS AssignmentNumber_ZUONR,
  SGTXT AS ItemText_SGTXT, ZINKZ AS ExemptedFromInterestCalculation_ZINKZ, VBUND AS CompanyIdOfTradingPartner_VBUND,
  BEWAR AS TransactionType_BEWAR, ALTKT AS GroupAccountNumber_ALTKT, VORGN AS TransactionTypeForGeneralLedger_VORGN,
  FDLEV AS PlanningLevel_FDLEV, FDGRP AS PlanningGroup_FDGRP, FDWBT AS PlannedAmountInDocumentOrGlAccountCurrency_FDWBT,
  FDTAG AS PlanningDate_FDTAG, FKONT AS FinancialBudgetItem_FKONT, KOKRS AS ControllingArea_KOKRS,
  KOSTL AS CostCenter_KOSTL, PROJN AS Old_ProjectNumberPs_posnr_PROJN, AUFNR AS OrderNumber_AUFNR,
  VBELN AS BillingDocument_VBELN, VBEL2 AS SalesDocument_VBEL2, POSN2 AS SalesDocumentItem_POSN2,
  ETEN2 AS ScheduleLineNumber_ETEN2, ANLN1 AS MainAssetNumber_ANLN1, ANLN2 AS AssetSubnumber_ANLN2,
  ANBWA AS AssetTransactionType_ANBWA, BZDAT AS AssetValueDate_BZDAT, PERNR AS PersonnelNumber_PERNR,
  XUMSW AS Indicator_SalesRelatedItem_XUMSW, XHRES AS Indicator_ResidentGlAccount_XHRES,
  XKRES AS Indicator_CanLineItemsBeDisplayedByAccount_XKRES, XOPVW AS Indicator_OpenItemManagement_XOPVW,
  XCPDD AS Indicator_AddressAndBankDataSetIndividually_XCPDD, XSKST AS Indicator_StatisticalPostingToCostCenter_XSKST,
  XSAUF AS Indicator_PostingToOrderIsStatistical_XSAUF, XSPRO AS Indicator_PostingToProjectIsStatistical_XSPRO,
  XSERG AS Indicator_PostingToProfitabilityAnalysisIsStatistical_XSERG, XFAKT AS Indicator_BillingDocumentUpdateSuccessful_XFAKT,
  XUMAN AS Indicator_TransferPostingFromDownPayment_XUMAN, XANET AS Indicator_DownPaymentInNetProcedure_XANET,
  XSKRL AS Indicator_LineItemNotLiableToCashDiscount_XSKRL, XINVE AS Indicator_CapitalGoodsAffected_XINVE,
  XPANZ AS DisplayItem_XPANZ, XAUTO AS Indicator_LineItemAutomaticallyCreated_XAUTO, XNCOP AS Indicator_ItemsCannotBeCopied_XNCOP,
  XZAHL AS Indicator_IsPostingUsedInAPaymentTransaction_XZAHL, SAKNR AS GlAccountNumber_SAKNR,
  HKONT AS GeneralLedgerAccount_HKONT, KUNNR AS CustomerNumber_KUNNR, LIFNR AS AccountNumberOfVendorOrCreditor_LIFNR,
  FILKD AS AccountNumberOfTheBranch_FILKD, XBILK AS Indicator_AccountIsABalanceSheetAccount_XBILK,
  GVTYP AS PLStatementAccountType_GVTYP, HZUON AS AssignmentNumberForSpecialGlAccounts_HZUON,
  ZFBDT AS BaselineDateForDueDateCalculation_ZFBDT, ZTERM AS TermsOfPayment_ZTERM, ZBD1T AS CashDiscountDays1_ZBD1T,
  ZBD2T AS CashDiscountDays2_ZBD2T, ZBD3T AS NetPaymentTermsPeriod_ZBD3T, ZBD1P AS CashDiscountPercentage1_ZBD1P,
  ZBD2P AS CashDiscountPercentage2_ZBD2P, SKFBT AS AmountEligibleForCashDiscountInDocumentCurrency_SKFBT,
  SKNTO AS CashDiscountAmountInLocalCurrency_SKNTO, WSKTO AS CashDiscountAmountInDocumentCurrency_WSKTO,
  ZLSCH AS PaymentMethod_ZLSCH, ZLSPR AS PaymentBlock_ZLSPR, ZBFIX AS FixedPaymentTerms_ZBFIX,
  HBKID AS ShortForAHouseBank_HBKID, BVTYP AS PartnerBankType_BVTYP, NEBTR AS NetPaymentAmount_NEBTR,
  MWSK1 AS TaxCodeForDistribution_MWSK1, DMBT1 AS AmountInLocalCurrencyForTaxDistribution_DMBT1,
  WRBT1 AS AmountInForeignCurrencyForTaxBreakdown_WRBT1, MWSK2 AS TaxCodeForDistribution_MWSK2,
  DMBT2 AS AmountInLocalCurrencyForTaxDistribution_DMBT2, WRBT2 AS AmountInForeignCurrencyForTaxBreakdown_WRBT2,
  MWSK3 AS TaxCodeForDistribution_MWSK3, DMBT3 AS AmountInLocalCurrencyForTaxDistribution_DMBT3,
  WRBT3 AS AmountInForeignCurrencyForTaxBreakdown_WRBT3, REBZG AS DocumentNoOfTheInvoiceToWhichTheTransactionBelongs_REBZG,
  REBZJ AS FiscalYearOfTheRelevantInvoice__forCreditMemo___REBZJ, REBZZ AS LineItemInTheRelevantInvoice_REBZZ,
  REBZT AS FollowOnDocumentType_REBZT, ZOLLT AS CustomsTariffNumber_ZOLLT, ZOLLD AS CustomsDate_ZOLLD,
  LZBKZ AS StateCentralBankIndicator_LZBKZ, LANDL AS SupplyingCountry_LANDL, DIEKZ AS ServiceIndicator__foreignPayment___DIEKZ,
  SAMNR AS InvoiceListNumber_SAMNR, ABPER AS SettlementPeriod_ABPER, VRSKZ AS InsuranceIndicator_VRSKZ,
  VRSDT AS InsuranceDate_VRSDT, DISBN AS NumberOfBillOfExchangeUsageDocument__discountDoc___DISBN,
  DISBJ AS FiscalYearOfBillOfExchangeUsageDocument_DISBJ, DISBZ AS LineItemWithinTheBillOfExchangeUsageDocument_DISBZ,
  WVERW AS BillOfExchangeUsageType_WVERW, ANFBN AS DocumentNumberOfTheBillOfExchangePaymentRequest_ANFBN,
  ANFBJ AS FiscalYearOfTheBillOfExchangePaymentRequestDocument_ANFBJ, ANFBU AS CompanyCodeInWhichBillOfExchPaymentRequestIsPosted_ANFBU,
  ANFAE AS BillOfExchangePaymentRequestDueDate_ANFAE, BLNBT AS BaseAmountForDeterminingThePreferenceAmount_BLNBT,
  BLNKZ AS SubsidyIndicatorForDeterminingTheReductionRates_BLNKZ, BLNPZ AS PreferencePercentageRate_BLNPZ,
  MSCHL AS Dunning_MSCHL, MANSP AS DunningBlock_MANSP, MADAT AS DateOfLastDunningNotice_MADAT,
  MANST AS DunningLevel_MANST, MABER AS DunningArea_MABER, ESRNR AS PorSubscriberNumber_ESRNR,
  ESRRE AS PorReferenceNumber_ESRRE, ESRPZ AS PorCheckDigit_ESRPZ, KLIBT AS CreditControlAmount_KLIBT,
  QSZNR AS CertificateNumberOfTheWithholdingTaxExemption_QSZNR, QBSHB AS WithholdingTaxAmount__inDocumentCurrency___QBSHB,
  QSFBT AS WithholdingTaxExemptAmount__inDocumentCurrency___QSFBT, NAVHW AS NonDeductibleInputTax__inLocalCurrency___NAVHW,
  NAVFW AS NonDeductibleInputTax__inDocumentCurrency___NAVFW, MATNR AS MaterialNumber_MATNR, WERKS AS Plant_WERKS,
  MENGE AS Quantity_MENGE, MEINS AS BaseUnitOfMeasure_MEINS, ERFMG AS QuantityInUnitOfEntry_ERFMG,
  ERFME AS UnitOfEntry_ERFME, BPMNG AS QuantityInPurchaseOrderPriceUnit_BPMNG, BPRME AS OrderPriceUnit__purchasing___BPRME,
  EBELN AS PurchasingDocumentNumber_EBELN, EBELP AS ItemNumberOfPurchasingDocument_EBELP,
  ZEKKN AS SequentialNumberOfAccountAssignment_ZEKKN, ELIKZ AS DeliveryCompletedIndicator_ELIKZ,
  VPRSV AS PriceControlIndicator_VPRSV, PEINH AS PriceUnit_PEINH, BW AS ValuationArea_BW,
  BWTAR AS ValuationType_BWTAR, BUSTW AS PostingStringForValues_BUSTW, REWRT AS InvoiceValueEntered__inLocalCurrency___REWRT,
  REWWR AS InvoiceValueInForeignCurrency_REWWR, BONFB AS AmountQualifyingForBonusInLocalCurrency_BONFB,
  BUALT AS AmountPostedInAlternativePriceControl_BUALT, PSALT AS AlternativePriceControl_PSALT, NPREI AS NewPrice_NPREI,
  TBTKZ AS Indicator_SubsequentDebitcredit_TBTKZ, SPGRP AS BlockingReason_Price_SPGRP, SPGRM AS BlockingReason_Quantity_SPGRM,
  SPGRT AS BlockingReason_Date_SPGRT, SPGRG AS BlockingReason_OrderPriceQuantity_SPGRG,
  SPGRV AS BlockingReason_ProjectBudget_SPGRV, SPGRQ AS ManualBlockingReason_SPGRQ, STCEG AS VatRegistrationNumber_STCEG,
  EGBLD AS CountryOfDestinationForDeliveryOfGoods_EGBLD, EGLLD AS SupplyingCountryForDeliveryOfGoods_EGLLD,
  RSTGR AS ReasonCodeForPayments_RSTGR, RYACQ AS YearOfAcquisition_RYACQ, RPACQ AS PeriodOfAcquisition_RPACQ,
  RDIFF AS ExchangeRateGainlossRealized_RDIFF, RDIF2 AS ExchangeRateDifferenceRealizedForSecondLocalCurrency_RDIF2,
  PRCTR AS ProfitCenter_PRCTR, XHKOM AS Indicator_GlAccountAssignedManually_XHKOM, VNAME AS JointVenture_VNAME,
  RECID AS RecoveryIndicator_RECID, EGRUP AS EquityGroup_EGRUP, VPTNR AS PartnerAccountNumber_VPTNR,
  VERTT AS ContractType_VERTT, VERTN AS ContractNumber_VERTN, VBEWA AS FlowType_VBEWA, DEPOT AS SecuritiesAccount_DEPOT,
  TXJCD AS TaxJurisdiction_TXJCD, IM AS InternalForRealEstateObject_IM, DABRZ AS ReferenceDateForSettlement_DABRZ,
  POPTS AS RealEstateOptionRate_POPTS, FIPOS AS CommitmentItem_FIPOS, KSTRG AS CostObject_KSTRG,
  NPLNR AS NetworkNumberForAccountAssignment_NPLNR, AUFPL AS TaskListNumberForOperationsInOrder_AUFPL,
  APLZL AS GeneralCounterForOrder_APLZL, PROJK AS WorkBreakdownStructureElement__wbsElement___PROJK,
  PAOBJNR AS ProfitabilitySegmentNumber__coPa___PAOBJNR, PASUBNR AS ProfitabilitySegmentChanges__coPa___PASUBNR,
  SPGRS AS BlockingReason_ItemAmount_SPGRS, SPGRC AS BlockingReason_Quality_SPGRC, BTYPE AS PayrollType_BTYPE,
  ETYPE AS EquityType_ETYPE, XEGDR AS Indicator_TriangularDealWithinTheEu_XEGDR,
  LNRAN AS SequenceNumberOfAssetLineItemsInFiscalYear_LNRAN, HRKFT AS OriginGroupAsSubdivisionOfCostElement_HRKFT,
  DMBE2 AS AmountInSecondLocalCurrency_DMBE2, DMBE3 AS AmountInThirdLocalCurrency_DMBE3,
  DMB21 AS AmountInSecondLocalCurrencyForTaxBreakdown_DMB21, DMB22 AS AmountInSecondLocalCurrencyForTaxBreakdown_DMB22,
  DMB23 AS AmountInSecondLocalCurrencyForTaxBreakdown_DMB23, DMB31 AS AmountInThirdLocalCurrencyForTaxBreakdown_DMB31,
  DMB32 AS AmountInThirdLocalCurrencyForTaxBreakdown_DMB32, DMB33 AS AmountInThirdLocalCurrencyForTaxBreakdown_DMB33,
  MWST2 AS TaxAmountInSecondLocalCurrency_MWST2, MWST3 AS TaxAmountInThirdLocalCurrency_MWST3,
  NAVH2 AS NonDeductibleInputTaxInSecondLocalCurrency_NAVH2, NAVH3 AS NonDeductibleInputTaxInThirdLocalCurrency_NAVH3,
  SKNT2 AS CashDiscountAmountInSecondLocalCurrency_SKNT2, SKNT3 AS CashDiscountAmountInThirdLocalCurrency_SKNT3,
  BDIF3 AS ValuationDifferenceForTheThirdLocalCurrency_BDIF3, RDIF3 AS ExchangeRateDifferenceRealizedForThirdLocalCurrency_RDIF3,
  HWMET AS MethodWithWhichTheLocalCurrencyAmountWasDetermined_HWMET, GLUPM AS UpdateMethodForFmFiCaIntegration_GLUPM,
  XRAGL AS Indicator_ClearingWasReversed_XRAGL, UZAWE AS PaymentMethodSupplement_UZAWE,
  LOKKT AS AlternativeAccountNumberInCompanyCode_LOKKT, FISTL AS FundsCenter_FISTL, GEBER AS Fund_GEBER,
  STBUK AS TaxCompanyCode_STBUK, TXBH2 AS TaxBaseoriginalTaxBaseInSecondLocalCurrency_TXBH2,
  TXBH3 AS TaxBaseoriginalTaxBaseInThirdLocalCurrency_TXBH3, PPRCT AS PartnerProfitCenter_PPRCT,
  XREF1 AS BusinessPartnerReference_XREF1, XREF2 AS BusinessPartnerReference_XREF2,
  KBLNR AS DocumentNumberForEarmarkedFunds_KBLNR, KBLPOS AS EarmarkedFunds_DocumentItem_KBLPOS,
  STTAX AS TaxAmountAsStatisticalInformationInDocumentCurrency_STTAX, FKBER AS FunctionalArea_FKBER,
  OBZEI AS NumberOfLineItemInOriginalDocument_OBZEI, XNEGP AS Indicator_NegativePosting_XNEGP, RFZEI AS PaymentCardItem_RFZEI,
  CCBTC AS PaymentCards_SettlementRun_CCBTC, KKBER AS CreditControlArea_KKBER, EMPFB AS Payeepayer_EMPFB,
  XREF3 AS ReferenceForLineItem_XREF3, DTWS1 AS Instruction1_DTWS1, DTWS2 AS Instruction2_DTWS2,
  DTWS3 AS Instruction3_DTWS3, DTWS4 AS Instruction4_DTWS4, GRICD AS ActivityCodeForGrossIncomeTax_GRICD,
  GRIRG AS Region_GRIRG, GITYP AS DistributionTypeForEmploymentTax_GITYP,
  XPYPR AS Indicator_ItemsFromPaymentProgramBlocked_XPYPR, KIDNO AS PaymentReference_KIDNO,
  ABSBT AS CreditManagement_HedgedAmount_ABSBT, IDXSP AS InflationIndex_IDXSP, LINFV AS LastAdjustmentDate_LINFV,
  KONTL AS AcctAssignmentStringForIndustrySpecificAcctAssignmnts_KONTL,
  TXDAT AS DateForDefiningTaxRates_TXDAT, AGZEI AS ClearingItem_AGZEI, PYCUR AS CurrencyForAutomaticPayment_PYCUR,
  PYAMT AS AmountInPaymentCurrency_PYAMT, BUPLA AS BusinessPlace_BUPLA, SECCO AS SectionCode_SECCO,
  LSTAR AS ActivityType_LSTAR, CESSION_KZ AS AccountsReceivablePledgingIndicator_CESSION_KZ, PRZNR AS BusinessProcess_PRZNR,
  PENLC2 AS PenaltyChargeAmountInSecondLocalCurrency_PENLC2, PENLC3 AS PenaltyChargeAmountInThirdLocalCurrency_PENLC3,
  PENFC AS PenaltyChargeAmountInDocumentCurrency_PENFC, PENDAYS AS NumberOfDaysForPenaltyChargeCalculation_PENDAYS,
  GRANT_NBR AS Grant_GRANT_NBR, SCTAX AS TaxPortionFiCaLocalCurrency_SCTAX,
  FKBER_LONG AS FunctionalArea_FKBER_LONG, GMVKZ AS ItemIsInExecution_GMVKZ, SRTYPE AS TypeOfAdditionalReceivable_SRTYPE,
  INTRENO AS InternalRealEstateMasterDataCode_INTRENO, MEASURE AS FundedProgram_MEASURE,
  AUGGJ AS FiscalYearOfClearingDocument_AUGGJ, PPA_EX_IND AS PpaExcludeIndicator_PPA_EX_IND,
  DOCLN AS SixCharacterPostingItemForLedger_DOCLN, SEGMENT AS SegmentForSegmentalReporting_SEGMENT,
  PSEGMENT AS PartnerSegmentForSegmentalReporting_PSEGMENT, PFKBER AS PartnerFunctionalArea_PFKBER,
  HKTID AS IdForAccountDetails_HKTID, KSTAR AS CostElement_KSTAR, XLGCLR AS ClearingSpecificToLedgerGroups_XLGCLR,
  TAXPS AS TaxDocumentItemNumber_TAXPS, PAYS_PROV AS PaymentServiceProvider_PAYS_PROV,
  PAYS_TRAN AS PaymentReferenceOfPaymentServiceProvider_PAYS_TRAN, MNDID AS UniqueReferenceToMandateForEachPayee_MNDID,
  XFRGE_BSEG AS PaymentIsReleased_XFRGE_BSEG, SQUAN AS QuantitySign_SQUAN, RE_BUKRS AS CashLedger_CompanyCodeForExpenserevenue_RE_BUKRS,
  RE_ACCOUNT AS CashLedger_ExpenseOrRevenueAccount_RE_ACCOUNT, PGEBER AS PartnerFund_PGEBER,
  PGRANT_NBR AS PartnerGrant_PGRANT_NBR, BUDGET_PD AS Fm_BudgetPeriod_BUDGET_PD, PBUDGET_PD AS Fm_PartnerBudgetPeriod_PBUDGET_PD,
  J_1TPBUPL AS BranchCode_J_1TPBUPL, PEROP_BEG AS BillingPeriodOfPerformanceStartDate_PEROP_BEG,
  PEROP_END AS BillingPeriodOfPerformanceEndDate_PEROP_END, FASTPAY AS PpaFastPayIndicator_FASTPAY,
  IGNR_IVREF AS Fmfg_IgnoreTheInvoiceReferenceDuringFiDocSplitting_IGNR_IVREF,
  FMFGUS_ AS UnitedStatesFederalGovernmentFields_FMFGUS_, FMXDOCNR AS FmReferenceDocumentNumber_FMXDOCNR,
  FMXYEAR AS FmReferenceYear_FMXYEAR, FMXDOCLN AS FmReferenceLineItem_FMXDOCLN,
  FMXZEKKN AS FmReferenceSequenceAccountAssignment_FMXZEKKN, PRODPER AS ProductionMonth__dateToFindPeriodAndYear___PRODPER,
  '  ' AS AccountAssignmentCategoryForIndustrySolution_KONTT, -- noqa: disable=L039
  '                                                  ' AS AcctAssignmentStringForIndustrySpecificAcctAssignmnts_KONTL,
  '     '      AS ReferenceProcedure_AWTYP,
  '          ' AS re_account,
  '00000000'   AS uebgdat,
  '          ' AS logsystem_sender,
  '    '       AS bukrs_sender,
  '          ' AS belnr_sender,
  '0000'       AS gjahr_sender,
  '000'        AS buzei_sender,
  '          ' AS bdgt_account
  FROM {{ project_id_src }}.{{ dataset_cdc_processed }}.bsad_bck WHERE xarch = 'X' -- noqa: enable=L039
  UNION ALL
{% endif %}
>>>>>>> main
SELECT BKPF.MANDT AS Client_MANDT, BKPF.BUKRS AS CompanyCode_BUKRS, BKPF.BELNR AS AccountingDocumentNumber_BELNR, BKPF.GJAHR AS FiscalYear_GJAHR,
  BSEG.BUZEI AS NumberOfLineItemWithinAccountingDocument_BUZEI, BSEG.BUZID AS IdentificationOfTheLineItem_BUZID,
  BSEG.AUGDT AS ClearingDate_AUGDT, BSEG.AUGCP AS ClearingEntryDate_AUGCP, BSEG.AUGBL AS DocumentNumberOfTheClearingDocument_AUGBL,
  BSEG.BSCHL AS Posting_BSCHL, BSEG.KOART AS AccountType_KOART, BSEG.UMSKZ AS SpecialGlIndicator_UMSKZ,
  BSEG.UMSKS AS SpecialGlTransactionType_UMSKS,
  BKPF.BLART AS DocumentType_BLART, BKPF.BLDAT AS DocumentDateInDocument_BLDAT, BKPF.BUDAT AS PostingDateInTheDocument_BUDAT,
  BKPF.MONAT AS FiscalPeriod_MONAT, BKPF.CPUDT AS DayOnWhichAccountingDocumentWasEntered_CPUDT, BKPF.CPUTM AS TimeOfEntry_CPUTM,
  BKPF.AEDAT AS DateOfTheLastDocumentChangeByTransaction_AEDAT, BKPF.UPDDT AS DateOfTheLastDocumentUpdate_UPDDT,
  BKPF.WWERT AS TranslationDate_WWERT, BKPF.USNAM AS UserName_USNAM, BKPF.TCODE AS TransactionCode_TCODE,
  BKPF.BVORG AS NumberOfACrossCompanyCodePostingTransaction_BVORG, BKPF.XBLNR AS ReferenceDocumentNumber_XBLNR,
  BKPF.DBBLG AS RecurringEntryDocumentNumber_DBBLG, BKPF.STBLG AS ReverseDocumentNumber_STBLG, BKPF.STJAH AS ReverseDocumentFiscalYear_STJAH,
  BKPF.BKTXT AS DocumentHeaderText_BKTXT, BKPF.WAERS AS Currency_WAERS, BKPF.KURSF AS ExchangeRate_KURSF,
  BKPF.KZWRS AS CurrencyForTheGroupCurrency_KZWRS, BKPF.KZKRS AS GroupCurrencyExchangeRate_KZKRS, BKPF.BSTAT AS DocumentStatus_BSTAT,
  BKPF.XNETB AS Indicator_DocumentPostedNet_XNETB, BKPF.FRATH AS UnplannedDeliveryCosts_FRATH,
  BKPF.XRUEB AS Indicator_DocumentIsPostedToAPreviousPeriod_XRUEB, BKPF.GLVOR AS BusinessTransaction_GLVOR,
  BKPF.GRPID AS BatchInputSessionName_GRPID, BKPF.DOKID AS DocumentNameInTheArchiveSystem_DOKID, BKPF.ARCID AS ExtractIdDocumentHeader_ARCID,
  BKPF.IBLAR AS InternalDocumentTypeForDocumentControl_IBLAR, BKPF.FIKRS AS FinancialManagementArea_FIKRS,
  BKPF.HWAER AS LocalCurrency_HWAER, BKPF.HWAE2 AS CurrencyOfSecondLocalCurrency_HWAE2,
  BKPF.HWAE3 AS CurrencyOfThirdLocalCurrency_HWAE3, BKPF.KURS2 AS ExchangeRateForTheSecondLocalCurrency_KURS2,
  BKPF.KURS3 AS ExchangeRateForTheThirdLocalCurrency_KURS3, BKPF.BASW2 AS SourceCurrencyForCurrencyTranslation_BASW2,
  BKPF.BASW3 AS SourceCurrencyForCurrencyTranslation_BASW3, BKPF.UMRD2 AS TranslationDateTypeForSecondLocalCurrency_UMRD2,
  BKPF.UMRD3 AS TranslationDateTypeForThirdLocalCurrency_UMRD3, BKPF.XSTOV AS Indicator_DocumentIsFlaggedForReversal_XSTOV,
  BKPF.STODT AS PlannedDateForTheReversePosting_STODT, BKPF.XMWST AS CalculateTaxAutomatically_XMWST,
  BKPF.CURT2 AS CurrencyTypeOfSecondLocalCurrency_CURT2, BKPF.CURT3 AS CurrencyTypeOfThirdLocalCurrency_CURT3,
  BKPF.KUTY2 AS ExchangeRateType_KUTY2, BKPF.KUTY3 AS ExchangeRateType_KUTY3, BKPF.XSNET AS GlAccountAmountsEnteredExcludeTax_XSNET,
  BKPF.AUSBK AS SourceCompanyCode_AUSBK, BKPF.DUEFL AS StatusOfDataTransferIntoSubsequentRelease_DUEFL, BKPF.AWSYS AS LogicalSystem_AWSYS, BKPF.TXKRS AS ExchangeRateForTaxes_TXKRS,
  BKPF.CTXKRS AS RateForTaxValuesInLocalCurrency__plantsAbroad___CTXKRS, BKPF.LOTKZ AS LotNumberForRequests_LOTKZ,
  BKPF.XWVOF AS Indicator_CustomerBillOfExchangePaymentBeforeDueDate_XWVOF, BKPF.STGRD AS ReasonForReversal_STGRD,
  BKPF.PPNAM AS NameOfUserWhoParkedThisDocument_PPNAM, BKPF.BRNCH AS BranchNumber_BRNCH, BKPF.NUMPG AS NumberOfPagesOfInvoice_NUMPG,
  BKPF.ADISC AS Indicator_EntryRepresentsADiscountDocument_ADISC, BKPF.XREF1_HD AS Reference1InternalForDocumentHeader_XREF1_HD,
  BKPF.XREF2_HD AS Reference2InternalForDocumentHeader_XREF2_HD, BKPF.XREVERSAL AS SpecifiesWhetherDocIsReversalDocOrReversedDoc_XREVERSAL,
  BKPF.REINDAT AS InvoiceReceiptDate_REINDAT, BKPF.RLDNR AS LedgerInGeneralLedgerAccounting_RLDNR, BKPF.LDGRP AS LedgerGroup_LDGRP,
  BKPF.PROPMANO AS RealEstateManagementMandate_PROPMANO, BKPF.XBLNR_ALT AS AlternativeReferenceNumber_XBLNR_ALT,
  BKPF.VATDATE AS TaxReportingDate_VATDATE, BKPF.DOCCAT AS ClassificationOfAnFiDocument_DOCCAT,
  BKPF.XSPLIT AS FiDocumentOriginatesFromSplitPosting__indicator___XSPLIT, BKPF.CASH_ALLOC AS CashRelevantDocument_CASH_ALLOC,
  BKPF.FOLLOW_ON AS FollowOnDocumentIndicator_FOLLOW_ON, BKPF.XREORG AS DocContainsOpenItemThatWasTransferredDuringReorg_XREORG,
  BKPF.SUBSET AS DefinesSubsetOfComponentsForTheFicoInterface_SUBSET, BKPF.KURST AS ExchangeRateType_KURST,
  BKPF.KURSX AS MarketDataExchangeRate_KURSX, BKPF.KUR2X AS MarketDataExchangeRate2_KUR2X, BKPF.KUR3X AS MarketDataExchangeRate3_KUR3X,
  BKPF.XMCA AS DocumentOriginatesFromMultiCurrencyAccounting_XMCA, BKPF.RESUBMISSION AS DateOfResubmission_RESUBMISSION,
  BKPF.PSOTY AS DocumentCategoryPaymentRequests_PSOTY, BKPF.PSOAK AS Reason_PSOAK,
  BKPF.PSOKS AS Region_PSOKS, BKPF.PSOSG AS ReasonForReversalIsPsRequests_PSOSG, BKPF.PSOFN AS IsPs_FileNumber_PSOFN,
  BKPF.INTFORM AS InterestFormula_INTFORM, BKPF.INTDATE AS InterestCalcDate_INTDATE, BKPF.PSOBT AS PostingDay_PSOBT,
  BKPF.PSOZL AS ActualPosting_PSOZL, BKPF.PSODT AS DateOfLastChange_PSODT, BKPF.PSOTM AS LastChangedAt_PSOTM,
  BKPF.FM_UMART AS TypeOfPaymentTransfer_FM_UMART, BKPF.CCINS AS PaymentCards_CardType_CCINS, BKPF.CCNUM AS PaymentCards_CardNumber_CCNUM,
  BKPF.SSBLK AS PaymentStatisticalSamplingBlock_SSBLK, BKPF.BATCH AS LotNumberForDocuments_BATCH, BKPF.SNAME AS UserName_SNAME,
  BKPF.SAMPLED AS SampledInvoiceByPaymentCertification_SAMPLED, BKPF.EXCLUDE_FLAG AS PpaExcludeIndicator_EXCLUDE_FLAG,
  BKPF.BLIND AS BudgetaryLedgerIndicator_BLIND, BKPF.OFFSET_STATUS AS TreasuryOffsetStatus_OFFSET_STATUS,
  BKPF.OFFSET_REFER_DAT AS DateRecordReferredToTreasury_OFFSET_REFER_DAT,
  BKPF.KNUMV AS NumberOfTheDocumentCondition_KNUMV,
  BSEG.ZUMSK AS TargetSpecialGlIndicator_ZUMSK, BSEG.shkzg AS DebitcreditIndicator_shkzg,
  BSEG.GSBER AS BusinessArea_GSBER, BSEG.PARGB AS TradingPartnerBusinessArea_PARGB, BSEG.MWSKZ AS TaxOnSalespurchasesCode_MWSKZ,
  BSEG.QSSKZ AS WithholdingTaxCode_QSSKZ,
  BSEG.KZBTR AS OriginalReductionAmountInLocalCurrency_KZBTR,
  BSEG.PSWBT AS AmountForUpdatingInGeneralLedger_PSWBT,
  BSEG.PSWSL AS UpdateCurrencyForGeneralLedgerTransactionFigures_PSWSL, BSEG.TXBHW AS OriginalTaxBaseAmountInLocalCurrency_TXBHW,
  BSEG.TXBFW AS OriginalTaxBaseAmountInDocumentCurrency_TXBFW, BSEG.MWSTS AS TaxAmountInLocalCurrency_MWSTS,
  BSEG.WMWST AS TaxAmountInDocumentCurrency_WMWST, BSEG.HWBAS AS TaxBaseAmountInLocalCurrency_HWBAS,
  BSEG.FWBAS AS TaxBaseAmountInDocumentCurrency_FWBAS, BSEG.HWZUZ AS ProvisionAmountInLocalCurrency_HWZUZ,
  BSEG.FWZUZ AS AdditionalTaxInDocumentCurrency_FWZUZ, BSEG.SHZUZ AS DebitcreditAdditionForCashDiscount_SHZUZ,
  BSEG.STEKZ AS VersionNumberComponent_STEKZ, BSEG.MWART AS TaxType_MWART,
  BSEG.TXGRP AS GroupIndicatorForTaxLineItems_TXGRP, BSEG.KTOSL AS Transaction_KTOSL, BSEG.QSSHB AS WithholdingTaxBaseAmount_QSSHB,
  BSEG.KURSR AS HedgedExchangeRate_KURSR, BSEG.GBETR AS HedgedAmountInForeignCurrency_GBETR, BSEG.BDIFF AS ValuationDifference_BDIFF,
  BSEG.BDIF2 AS ValuationDifferenceForTheSecondLocalCurrency_BDIF2, BSEG.VALUT AS ValueDate_VALUT,
  BSEG.ZUONR AS AssignmentNumber_ZUONR, BSEG.SGTXT AS ItemText_SGTXT, BSEG.ZINKZ AS ExemptedFromInterestCalculation_ZINKZ,
  BSEG.VBUND AS CompanyIdOfTradingPartner_VBUND, BSEG.BEWAR AS TransactionType_BEWAR, BSEG.ALTKT AS GroupAccountNumber_ALTKT,
  BSEG.VORGN AS TransactionTypeForGeneralLedger_VORGN, BSEG.FDLEV AS PlanningLevel_FDLEV, BSEG.FDGRP AS PlanningGroup_FDGRP,
  BSEG.FDWBT AS PlannedAmountInDocumentOrGlAccountCurrency_FDWBT, BSEG.FDTAG AS PlanningDate_FDTAG, BSEG.FKONT AS FinancialBudgetItem_FKONT,
  BSEG.KOKRS AS ControllingArea_KOKRS, BSEG.KOSTL AS CostCenter_KOSTL, BSEG.PROJN AS Old_ProjectNumberPs_posnr_PROJN,
  BSEG.AUFNR AS OrderNumber_AUFNR, BSEG.VBELN AS BillingDocument_VBELN, BSEG.VBEL2 AS SalesDocument_VBEL2,
  BSEG.POSN2 AS SalesDocumentItem_POSN2, BSEG.ETEN2 AS ScheduleLineNumber_ETEN2, BSEG.ANLN1 AS MainAssetNumber_ANLN1,
  BSEG.ANLN2 AS AssetSubnumber_ANLN2, BSEG.ANBWA AS AssetTransactionType_ANBWA, BSEG.BZDAT AS AssetValueDate_BZDAT,
  BSEG.PERNR AS PersonnelNumber_PERNR, BSEG.XUMSW AS Indicator_SalesRelatedItem_XUMSW, BSEG.XHRES AS Indicator_ResidentGlAccount_XHRES,
  BSEG.XKRES AS Indicator_CanLineItemsBeDisplayedByAccount_XKRES, BSEG.XOPVW AS Indicator_OpenItemManagement_XOPVW,
  BSEG.XCPDD AS Indicator_AddressAndBankDataSetIndividually_XCPDD, BSEG.XSKST AS Indicator_StatisticalPostingToCostCenter_XSKST,
  BSEG.XSAUF AS Indicator_PostingToOrderIsStatistical_XSAUF, BSEG.XSPRO AS Indicator_PostingToProjectIsStatistical_XSPRO,
  BSEG.XSERG AS Indicator_PostingToProfitabilityAnalysisIsStatistical_XSERG, BSEG.XFAKT AS Indicator_BillingDocumentUpdateSuccessful_XFAKT,
  BSEG.XUMAN AS Indicator_TransferPostingFromDownPayment_XUMAN, BSEG.XANET AS Indicator_DownPaymentInNetProcedure_XANET,
  BSEG.XSKRL AS Indicator_LineItemNotLiableToCashDiscount_XSKRL, BSEG.XINVE AS Indicator_CapitalGoodsAffected_XINVE,
  BSEG.XPANZ AS DisplayItem_XPANZ, BSEG.XAUTO AS Indicator_LineItemAutomaticallyCreated_XAUTO,
  BSEG.XNCOP AS Indicator_ItemsCannotBeCopied_XNCOP, BSEG.XZAHL AS Indicator_IsPostingUsedInAPaymentTransaction_XZAHL, BSEG.SAKNR AS GlAccountNumber_SAKNR,
  BSEG.HKONT AS GeneralLedgerAccount_HKONT, BSEG.KUNNR AS CustomerNumber_KUNNR,
  BSEG.LIFNR AS AccountNumberOfVendorOrCreditor_LIFNR, BSEG.FILKD AS AccountNumberOfTheBranch_FILKD, BSEG.XBILK AS Indicator_AccountIsABalanceSheetAccount_XBILK,
  BSEG.GVTYP AS PLStatementAccountType_GVTYP, BSEG.HZUON AS AssignmentNumberForSpecialGlAccounts_HZUON,
  BSEG.ZFBDT AS BaselineDateForDueDateCalculation_ZFBDT, BSEG.ZTERM AS TermsOfPayment_ZTERM,
  BSEG.ZBD1T AS CashDiscountDays1_ZBD1T, BSEG.ZBD2T AS CashDiscountDays2_ZBD2T, BSEG.ZBD3T AS NetPaymentTermsPeriod_ZBD3T,
  BSEG.ZBD1P AS CashDiscountPercentage1_ZBD1P, BSEG.ZBD2P AS CashDiscountPercentage2_ZBD2P, BSEG.SKFBT AS AmountEligibleForCashDiscountInDocumentCurrency_SKFBT,
  BSEG.SKNTO AS CashDiscountAmountInLocalCurrency_SKNTO, BSEG.WSKTO AS CashDiscountAmountInDocumentCurrency_WSKTO,
  BSEG.ZLSCH AS PaymentMethod_ZLSCH, BSEG.ZLSPR AS PaymentBlock_ZLSPR,
  BSEG.ZBFIX AS FixedPaymentTerms_ZBFIX, BSEG.HBKID AS ShortForAHouseBank_HBKID, BSEG.BVTYP AS PartnerBankType_BVTYP,
  BSEG.NEBTR AS NetPaymentAmount_NEBTR, BSEG.MWSK1 AS TaxCodeForDistribution_MWSK1, BSEG.DMBT1 AS AmountInLocalCurrencyForTaxDistribution_DMBT1,
  BSEG.WRBT1 AS AmountInForeignCurrencyForTaxBreakdown_WRBT1, BSEG.MWSK2 AS TaxCodeForDistribution_MWSK2,
  BSEG.DMBT2 AS AmountInLocalCurrencyForTaxDistribution_DMBT2, BSEG.WRBT2 AS AmountInForeignCurrencyForTaxBreakdown_WRBT2,
  BSEG.MWSK3 AS TaxCodeForDistribution_MWSK3, BSEG.DMBT3 AS AmountInLocalCurrencyForTaxDistribution_DMBT3,
  BSEG.WRBT3 AS AmountInForeignCurrencyForTaxBreakdown_WRBT3, BSEG.REBZG AS DocumentNoOfTheInvoiceToWhichTheTransactionBelongs_REBZG,
  BSEG.REBZJ AS FiscalYearOfTheRelevantInvoice__forCreditMemo___REBZJ, BSEG.REBZZ AS LineItemInTheRelevantInvoice_REBZZ,
  BSEG.REBZT AS FollowOnDocumentType_REBZT, BSEG.ZOLLT AS CustomsTariffNumber_ZOLLT,
  BSEG.ZOLLD AS CustomsDate_ZOLLD, BSEG.LZBKZ AS StateCentralBankIndicator_LZBKZ, BSEG.LANDL AS SupplyingCountry_LANDL,
  BSEG.DIEKZ AS ServiceIndicator__foreignPayment___DIEKZ, BSEG.SAMNR AS InvoiceListNumber_SAMNR, BSEG.ABPER AS SettlementPeriod_ABPER,
  BSEG.VRSKZ AS InsuranceIndicator_VRSKZ, BSEG.VRSDT AS InsuranceDate_VRSDT, BSEG.DISBN AS NumberOfBillOfExchangeUsageDocument__discountDoc___DISBN,
  BSEG.DISBJ AS FiscalYearOfBillOfExchangeUsageDocument_DISBJ, BSEG.DISBZ AS LineItemWithinTheBillOfExchangeUsageDocument_DISBZ,
  BSEG.WVERW AS BillOfExchangeUsageType_WVERW, BSEG.ANFBN AS DocumentNumberOfTheBillOfExchangePaymentRequest_ANFBN,
  BSEG.ANFBJ AS FiscalYearOfTheBillOfExchangePaymentRequestDocument_ANFBJ, BSEG.ANFBU AS CompanyCodeInWhichBillOfExchPaymentRequestIsPosted_ANFBU,
  BSEG.ANFAE AS BillOfExchangePaymentRequestDueDate_ANFAE, BSEG.BLNBT AS BaseAmountForDeterminingThePreferenceAmount_BLNBT,
  BSEG.BLNKZ AS SubsidyIndicatorForDeterminingTheReductionRates_BLNKZ, BSEG.BLNPZ AS PreferencePercentageRate_BLNPZ,
  BSEG.MSCHL AS Dunning_MSCHL, BSEG.MANSP AS DunningBlock_MANSP,
  BSEG.MADAT AS DateOfLastDunningNotice_MADAT, BSEG.MANST AS DunningLevel_MANST, BSEG.MABER AS DunningArea_MABER,
  BSEG.ESRNR AS PorSubscriberNumber_ESRNR, BSEG.ESRRE AS PorReferenceNumber_ESRRE, BSEG.ESRPZ AS PorCheckDigit_ESRPZ,
  BSEG.KLIBT AS CreditControlAmount_KLIBT, BSEG.QSZNR AS CertificateNumberOfTheWithholdingTaxExemption_QSZNR, BSEG.QBSHB AS WithholdingTaxAmount__inDocumentCurrency___QBSHB,
  BSEG.QSFBT AS WithholdingTaxExemptAmount__inDocumentCurrency___QSFBT, BSEG.NAVHW AS NonDeductibleInputTax__inLocalCurrency___NAVHW,
  BSEG.NAVFW AS NonDeductibleInputTax__inDocumentCurrency___NAVFW, BSEG.MATNR AS MaterialNumber_MATNR,
  BSEG.WERKS AS Plant_WERKS, BSEG.MENGE AS Quantity_MENGE, BSEG.MEINS AS BaseUnitOfMeasure_MEINS,
  BSEG.ERFMG AS QuantityInUnitOfEntry_ERFMG, BSEG.ERFME AS UnitOfEntry_ERFME, BSEG.BPMNG AS QuantityInPurchaseOrderPriceUnit_BPMNG,
  BSEG.BPRME AS OrderPriceUnit__purchasing___BPRME, BSEG.EBELN AS PurchasingDocumentNumber_EBELN, BSEG.EBELP AS ItemNumberOfPurchasingDocument_EBELP,
  BSEG.ZEKKN AS SequentialNumberOfAccountAssignment_ZEKKN, BSEG.ELIKZ AS DeliveryCompletedIndicator_ELIKZ,
  BSEG.VPRSV AS PriceControlIndicator_VPRSV, BSEG.PEINH AS PriceUnit_PEINH,
  BSEG.BWTAR AS ValuationType_BWTAR, BSEG.BUSTW AS PostingStringForValues_BUSTW,
  BSEG.REWRT AS InvoiceValueEntered__inLocalCurrency___REWRT, BSEG.REWWR AS InvoiceValueInForeignCurrency_REWWR, BSEG.BONFB AS AmountQualifyingForBonusInLocalCurrency_BONFB,
  BSEG.BUALT AS AmountPostedInAlternativePriceControl_BUALT, BSEG.PSALT AS AlternativePriceControl_PSALT,
  BSEG.NPREI AS NewPrice_NPREI, BSEG.TBTKZ AS Indicator_SubsequentDebitcredit_TBTKZ, BSEG.SPGRP AS BlockingReason_Price_SPGRP,
  BSEG.SPGRM AS BlockingReason_Quantity_SPGRM, BSEG.SPGRT AS BlockingReason_Date_SPGRT, BSEG.SPGRG AS BlockingReason_OrderPriceQuantity_SPGRG,
  BSEG.SPGRV AS BlockingReason_ProjectBudget_SPGRV, BSEG.SPGRQ AS ManualBlockingReason_SPGRQ,
  BSEG.STCEG AS VatRegistrationNumber_STCEG, BSEG.EGBLD AS CountryOfDestinationForDeliveryOfGoods_EGBLD, BSEG.EGLLD AS SupplyingCountryForDeliveryOfGoods_EGLLD,
  BSEG.RSTGR AS ReasonCodeForPayments_RSTGR, BSEG.RYACQ AS YearOfAcquisition_RYACQ,
  BSEG.RPACQ AS PeriodOfAcquisition_RPACQ, BSEG.RDIFF AS ExchangeRateGainlossRealized_RDIFF, BSEG.RDIF2 AS ExchangeRateDifferenceRealizedForSecondLocalCurrency_RDIF2,
  BSEG.PRCTR AS ProfitCenter_PRCTR, BSEG.XHKOM AS Indicator_GlAccountAssignedManually_XHKOM,
  BSEG.VNAME AS JointVenture_VNAME, BSEG.RECID AS RecoveryIndicator_RECID, BSEG.EGRUP AS EquityGroup_EGRUP,
  BSEG.VPTNR AS PartnerAccountNumber_VPTNR, BSEG.VERTT AS ContractType_VERTT, BSEG.VERTN AS ContractNumber_VERTN,
  BSEG.VBEWA AS FlowType_VBEWA, BSEG.DEPOT AS SecuritiesAccount_DEPOT, BSEG.TXJCD AS TaxJurisdiction_TXJCD,
  BSEG.DABRZ AS ReferenceDateForSettlement_DABRZ, BSEG.POPTS AS RealEstateOptionRate_POPTS, BSEG.FIPOS AS CommitmentItem_FIPOS,
  BSEG.KSTRG AS CostObject_KSTRG, BSEG.NPLNR AS NetworkNumberForAccountAssignment_NPLNR, BSEG.AUFPL AS TaskListNumberForOperationsInOrder_AUFPL,
  BSEG.APLZL AS GeneralCounterForOrder_APLZL, BSEG.PROJK AS WorkBreakdownStructureElement__wbsElement___PROJK,
  BSEG.PAOBJNR AS ProfitabilitySegmentNumber__coPa___PAOBJNR, BSEG.PASUBNR AS ProfitabilitySegmentChanges__coPa___PASUBNR,
  BSEG.SPGRS AS BlockingReason_ItemAmount_SPGRS, BSEG.SPGRC AS BlockingReason_Quality_SPGRC,
  BSEG.BTYPE AS PayrollType_BTYPE, BSEG.ETYPE AS EquityType_ETYPE, BSEG.XEGDR AS Indicator_TriangularDealWithinTheEu_XEGDR,
  BSEG.LNRAN AS SequenceNumberOfAssetLineItemsInFiscalYear_LNRAN, BSEG.HRKFT AS OriginGroupAsSubdivisionOfCostElement_HRKFT,
  BSEG.DMBE2 AS AmountInSecondLocalCurrency_DMBE2, BSEG.DMBE3 AS AmountInThirdLocalCurrency_DMBE3,
  BSEG.DMB21 AS AmountInSecondLocalCurrencyForTaxBreakdown_DMB21, BSEG.DMB22 AS AmountInSecondLocalCurrencyForTaxBreakdown_DMB22,
  BSEG.DMB23 AS AmountInSecondLocalCurrencyForTaxBreakdown_DMB23, BSEG.DMB31 AS AmountInThirdLocalCurrencyForTaxBreakdown_DMB31,
  BSEG.DMB32 AS AmountInThirdLocalCurrencyForTaxBreakdown_DMB32, BSEG.DMB33 AS AmountInThirdLocalCurrencyForTaxBreakdown_DMB33,
  BSEG.MWST2 AS TaxAmountInSecondLocalCurrency_MWST2, BSEG.MWST3 AS TaxAmountInThirdLocalCurrency_MWST3,
  BSEG.NAVH2 AS NonDeductibleInputTaxInSecondLocalCurrency_NAVH2, BSEG.NAVH3 AS NonDeductibleInputTaxInThirdLocalCurrency_NAVH3,
  BSEG.SKNT2 AS CashDiscountAmountInSecondLocalCurrency_SKNT2, BSEG.SKNT3 AS CashDiscountAmountInThirdLocalCurrency_SKNT3,
  BSEG.BDIF3 AS ValuationDifferenceForTheThirdLocalCurrency_BDIF3, BSEG.RDIF3 AS ExchangeRateDifferenceRealizedForThirdLocalCurrency_RDIF3,
  BSEG.HWMET AS MethodWithWhichTheLocalCurrencyAmountWasDetermined_HWMET, BSEG.GLUPM AS UpdateMethodForFmFiCaIntegration_GLUPM,
  BSEG.XRAGL AS Indicator_ClearingWasReversed_XRAGL, BSEG.UZAWE AS PaymentMethodSupplement_UZAWE,
  BSEG.LOKKT AS AlternativeAccountNumberInCompanyCode_LOKKT, BSEG.FISTL AS FundsCenter_FISTL,
  BSEG.GEBER AS Fund_GEBER, BSEG.STBUK AS TaxCompanyCode_STBUK, BSEG.TXBH2 AS TaxBaseoriginalTaxBaseInSecondLocalCurrency_TXBH2,
  BSEG.TXBH3 AS TaxBaseoriginalTaxBaseInThirdLocalCurrency_TXBH3, BSEG.PPRCT AS PartnerProfitCenter_PPRCT,
  BSEG.XREF1 AS BusinessPartnerReference_XREF1, BSEG.XREF2 AS BusinessPartnerReference_XREF2,
  BSEG.KBLNR AS DocumentNumberForEarmarkedFunds_KBLNR, BSEG.KBLPOS AS EarmarkedFunds_DocumentItem_KBLPOS,
  BSEG.STTAX AS TaxAmountAsStatisticalInformationInDocumentCurrency_STTAX, BSEG.FKBER AS FunctionalArea_FKBER,
  BSEG.OBZEI AS NumberOfLineItemInOriginalDocument_OBZEI, BSEG.XNEGP AS Indicator_NegativePosting_XNEGP,
  BSEG.RFZEI AS PaymentCardItem_RFZEI, BSEG.CCBTC AS PaymentCards_SettlementRun_CCBTC, BSEG.KKBER AS CreditControlArea_KKBER,
  BSEG.EMPFB AS Payeepayer_EMPFB, BSEG.XREF3 AS ReferenceForLineItem_XREF3, BSEG.DTWS1 AS Instruction1_DTWS1,
  BSEG.DTWS2 AS Instruction2_DTWS2, BSEG.DTWS3 AS Instruction3_DTWS3, BSEG.DTWS4 AS Instruction4_DTWS4,
  BSEG.GRICD AS ActivityCodeForGrossIncomeTax_GRICD, BSEG.GRIRG AS Region_GRIRG, BSEG.GITYP AS DistributionTypeForEmploymentTax_GITYP,
  BSEG.XPYPR AS Indicator_ItemsFromPaymentProgramBlocked_XPYPR, BSEG.KIDNO AS PaymentReference_KIDNO,
  BSEG.ABSBT AS CreditManagement_HedgedAmount_ABSBT, BSEG.IDXSP AS InflationIndex_IDXSP,
  BSEG.LINFV AS LastAdjustmentDate_LINFV, BSEG.TXDAT AS DateForDefiningTaxRates_TXDAT,
  BSEG.AGZEI AS ClearingItem_AGZEI,
  BSEG.PYCUR AS CurrencyForAutomaticPayment_PYCUR, BSEG.PYAMT AS AmountInPaymentCurrency_PYAMT,
  BSEG.BUPLA AS BusinessPlace_BUPLA,
  BSEG.SECCO AS SectionCode_SECCO, BSEG.LSTAR AS ActivityType_LSTAR,
  BSEG.CESSION_KZ AS AccountsReceivablePledgingIndicator_CESSION_KZ,
  BSEG.PRZNR AS BusinessProcess_PRZNR, BSEG.PENLC2 AS PenaltyChargeAmountInSecondLocalCurrency_PENLC2, BSEG.PENLC3 AS PenaltyChargeAmountInThirdLocalCurrency_PENLC3,
  BSEG.PENFC AS PenaltyChargeAmountInDocumentCurrency_PENFC, BSEG.PENDAYS AS NumberOfDaysForPenaltyChargeCalculation_PENDAYS,
  BSEG.PENRC AS ReasonForLatePayment_PENRC, BSEG.GRANT_NBR AS Grant_GRANT_NBR,
  BSEG.SCTAX AS TaxPortionFiCaLocalCurrency_SCTAX, BSEG.FKBER_LONG AS FunctionalArea_FKBER_LONG, BSEG.GMVKZ AS ItemIsInExecution_GMVKZ,
  BSEG.SRTYPE AS TypeOfAdditionalReceivable_SRTYPE, BSEG.INTRENO AS InternalRealEstateMasterDataCode_INTRENO, BSEG.MEASURE AS FundedProgram_MEASURE,
  BSEG.AUGGJ AS FiscalYearOfClearingDocument_AUGGJ, BSEG.PPA_EX_IND AS PpaExcludeIndicator_PPA_EX_IND,
  BSEG.DOCLN AS SixCharacterPostingItemForLedger_DOCLN, BSEG.SEGMENT AS SegmentForSegmentalReporting_SEGMENT,
  BSEG.PSEGMENT AS PartnerSegmentForSegmentalReporting_PSEGMENT, BSEG.PFKBER AS PartnerFunctionalArea_PFKBER,
  BSEG.HKTID AS IdForAccountDetails_HKTID, BSEG.KSTAR AS CostElement_KSTAR,
  BSEG.XLGCLR AS ClearingSpecificToLedgerGroups_XLGCLR, BSEG.TAXPS AS TaxDocumentItemNumber_TAXPS, BSEG.PAYS_PROV AS PaymentServiceProvider_PAYS_PROV,
  BSEG.PAYS_TRAN AS PaymentReferenceOfPaymentServiceProvider_PAYS_TRAN, BSEG.MNDID AS UniqueReferenceToMandateForEachPayee_MNDID,
  BSEG.XFRGE_BSEG AS PaymentIsReleased_XFRGE_BSEG, BSEG.SQUAN AS QuantitySign_SQUAN,
<<<<<<< HEAD
  BSEG.ZZSPREG AS SpecialRegion_ZZSPREG, BSEG.ZZBUSPARTN AS BusinessPartner_ZZBUSPARTN, BSEG.ZZCHAN AS DistributionChannel_ZZCHAN,
  BSEG.ZZPRODUCT AS ProductGroup_ZZPRODUCT, BSEG.ZZLOCA AS City_ZZLOCA, BSEG.ZZLOB AS BusinessLine_ZZLOB,
  BSEG.ZZUSERFLD1 AS Territory_ZZUSERFLD1, BSEG.ZZUSERFLD2 AS Ownercont_ZZUSERFLD2, BSEG.ZZUSERFLD3 AS Vein_ZZUSERFLD3,
  BSEG.ZZSTATE AS StateprovinceCode_ZZSTATE, BSEG.ZZREGION AS Location_ZZREGION, BSEG.RE_BUKRS AS CashLedger_CompanyCodeForExpenserevenue_RE_BUKRS,
=======
  -- BSEG.ZZSPREG AS SpecialRegion_ZZSPREG, BSEG.ZZBUSPARTN AS BusinessPartner_ZZBUSPARTN, BSEG.ZZCHAN AS DistributionChannel_ZZCHAN,
  -- BSEG.ZZPRODUCT AS ProductGroup_ZZPRODUCT, BSEG.ZZLOCA AS City_ZZLOCA, BSEG.ZZLOB AS BusinessLine_ZZLOB,
  -- BSEG.ZZUSERFLD1 AS Territory_ZZUSERFLD1, BSEG.ZZUSERFLD2 AS Ownercont_ZZUSERFLD2, BSEG.ZZUSERFLD3 AS Vein_ZZUSERFLD3,
  -- BSEG.ZZSTATE AS StateprovinceCode_ZZSTATE, BSEG.ZZREGION AS Location_ZZREGION, 
  BSEG.RE_BUKRS AS CashLedger_CompanyCodeForExpenserevenue_RE_BUKRS,
>>>>>>> main
  BSEG.RE_ACCOUNT AS CashLedger_ExpenseOrRevenueAccount_RE_ACCOUNT, BSEG.PGEBER AS PartnerFund_PGEBER,
  BSEG.PGRANT_NBR AS PartnerGrant_PGRANT_NBR, BSEG.BUDGET_PD AS Fm_BudgetPeriod_BUDGET_PD,
  BSEG.PBUDGET_PD AS Fm_PartnerBudgetPeriod_PBUDGET_PD, BSEG.J_1TPBUPL AS BranchCode_J_1TPBUPL, BSEG.PEROP_BEG AS BillingPeriodOfPerformanceStartDate_PEROP_BEG,
  BSEG.PEROP_END AS BillingPeriodOfPerformanceEndDate_PEROP_END, BSEG.FASTPAY AS PpaFastPayIndicator_FASTPAY,
  BSEG.IGNR_IVREF AS Fmfg_IgnoreTheInvoiceReferenceDuringFiDocSplitting_IGNR_IVREF,
  BSEG.FMXDOCNR AS FmReferenceDocumentNumber_FMXDOCNR,
  BSEG.FMXYEAR AS FmReferenceYear_FMXYEAR, BSEG.FMXDOCLN AS FmReferenceLineItem_FMXDOCLN,
  BSEG.FMXZEKKN AS FmReferenceSequenceAccountAssignment_FMXZEKKN, BSEG.PRODPER AS ProductionMonth__dateToFindPeriodAndYear___PRODPER,
  BSEG.KONTT AS AccountAssignmentCategoryForIndustrySolution_KONTT, bseg.kontl AS AcctAssignmentStringForIndustrySpecificAcctAssignmnts_KONTL,
  bkpf.awtyp AS ReferenceProcedure_AWTYP,
  CASE
    WHEN bseg.shkzg = 'S' THEN bseg.dmbtr  -- S = Debit | Amount in document currency
    WHEN bseg.shkzg = 'H' THEN bseg.dmbtr * -1  -- H = Credit | Amount in document currency
    ELSE bseg.dmbtr
  END AS AmountInLocalCurrency_dmbtr,
  CASE
    WHEN bseg.shkzg = 'S' THEN bseg.wrbtr  -- S = Debit | Amount in document currency
    WHEN bseg.shkzg = 'H' THEN bseg.wrbtr * -1  -- H = Credit | Amount in document currency
    ELSE bseg.wrbtr
<<<<<<< HEAD
  END AS AmountInDocumentCurrency_wrbtr --##S4##,
--##S4##  BSEG.re_account,
--##S4##    '00000000' as uebgdat,
--##S4##    '          ' as logsystem_sender,
--##S4##    '    '       as bukrs_sender,
--##S4##    '          ' as belnr_sender,
--##S4##    '0000'       as gjahr_sender,
--##S4##    '000'        as buzei_sender,
--##S4## BSEG.BDGT_ACCOUNT, 
=======
  END AS AmountInDocumentCurrency_wrbtr{% if sql_flavour.upper() == 'S4' %},
    BSEG.re_account,
    '00000000' AS uebgdat, -- noqa: disable=L039
    '          ' AS logsystem_sender,
    '    '       AS bukrs_sender,
    '          ' AS belnr_sender,
    '0000'       AS gjahr_sender,
    '000'        AS buzei_sender,
    BSEG.BDGT_ACCOUNT -- noqa: enable=L039
  {% endif %}
>>>>>>> main
FROM `{{ project_id_src }}.{{ dataset_cdc_processed }}.bkpf` AS bkpf
LEFT OUTER JOIN `{{ project_id_src }}.{{ dataset_cdc_processed }}.bseg` AS bseg
  ON bkpf.mandt = bseg.mandt
    AND bkpf.bukrs = bseg.bukrs
    AND bkpf.gjahr = bseg.gjahr
    AND bkpf.belnr = bseg.belnr
WHERE bseg.koart = 'D'
  AND bseg.augbl IS NULL
<<<<<<< HEAD
--##S4## and bseg.h_bstat <> 'D'
--##S4## and bseg.h_bstat <> 'M'
=======
  {% if sql_flavour.upper() == 'S4' %}
    AND bseg.h_bstat != 'D'
    AND bseg.h_bstat != 'M'
  {% endif %}
>>>>>>> main
