#-- Copyright 2022 Google LLC
#--
#-- Licensed under the Apache License, Version 2.0 (the "License");
#-- you may not use this file except in compliance with the License.
#-- You may obtain a copy of the License at
#--
#--     https://www.apache.org/licenses/LICENSE-2.0
#--
#-- Unless required by applicable law or agreed to in writing, software
#-- distributed under the License is distributed on an "AS IS" BASIS,
#-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#-- See the License for the specific language governing permissions and
#-- limitations under the License.
CREATE OR REPLACE VIEW `{{ project_id_tgt }}.{{ dataset_reporting_tgt }}.SalesOrders`
OPTIONS(
  description = "Sales Orders Header and Items"
)
AS

WITH
TCURX AS (
  -- Joining to this table is necesssary to fix the decimal place of 
  -- amounts for non-decimal-based currencies. SAP stores these amounts 
  -- offset by a factor  of 1/100 within the system (FYI this gets 
  -- corrected when a user observes these in the GUI) Currencies w/ 
  -- decimals are unimpacted.
  --
  -- Example of impacted currencies JPY, IDR, KRW, TWD 
  -- Example of non-impacted currencies USD, GBP, EUR
  -- Example 1,000 JPY will appear as 10.00 JPY
  SELECT DISTINCT
    CURRKEY,
    CAST(POWER(10, 2 - COALESCE(CURRDEC, 0)) AS NUMERIC) AS CURRFIX
  FROM
    --   `{{ project_id_src }}.{{ dataset_cdc_processed }}.tcurx` 
    `{{ project_id_src }}.{{ dataset_cdc_processed }}.tcurx`
),


CONV AS (
  -- This table is used to convert rates from the transaction currency to USD.
  SELECT DISTINCT
    mandt,
    fcurr,
    tcurr,
    ukurs,
    PARSE_DATE("%Y%m%d", CAST(99999999 - CAST(gdatu AS INT64) AS STRING)) AS gdatu
  FROM `{{ project_id_src }}.{{ dataset_cdc_processed }}.tcurr`
  WHERE
    mandt = '{{ mandt }}'
    AND kurst = 'M' -- Daily Corporate Rate
    AND tcurr = 'USD' -- Convert to USD

  UNION ALL

  -- USD to USD rates do not exist in TCURR (or any other rates that are same-to-
  -- same such as EUR to EUR / JPY to JPY etc.
  SELECT
    '{{ mandt }}' AS mandt,
    'USD' AS fcurr,
    'USD' AS tcurr,
    1 AS ukurs,
    date_array AS gdatu
  FROM
    UNNEST(GENERATE_DATE_ARRAY('1990-01-01', '2060-12-31')) AS date_array
)

SELECT
  vbak.MANDT AS Client_MANDT,
  vbak.VBELN AS SalesDocument_VBELN,
  vbap.POSNR AS Item_POSNR,
  vbap.MATNR AS MaterialNumber_MATNR,
  vbak.ERDAT AS CreationDate_ERDAT,
  vbak.ERZET AS CreationTime_ERZET,
  vbak.ERNAM AS CreatedBy_ERNAM,
  vbak.ANGDT AS QuotationDateFrom_ANGDT,
  vbak.BNDDT AS QuotationDateTo_BNDDT,
  vbak.AUDAT AS DocumentDate_AUDAT,
  vbak.VBTYP AS DocumentCategory_VBTYP,
  vbak.TRVOG AS TransactionGroup_TRVOG,
  vbak.AUART AS SalesDocumentType_AUART,
  vbak.AUGRU AS Reason_AUGRU,
  vbak.GWLDT AS WarrantyDate_GWLDT,
  vbak.SUBMI AS Collectivenumber_SUBMI,
  vbak.LIFSK AS Deliveryblock_LIFSK,
  vbak.FAKSK AS Billingblock_FAKSK,
  vbak.WAERK AS CurrencyHdr_WAERK,
  vbak.VKORG AS SalesOrganization_VKORG,
  vbak.VTWEG AS DistributionChannel_VTWEG,
  vbak.SPART AS DivisionHdr_SPART,
  vbak.VKGRP AS SalesGroup_VKGRP,
  vbak.VKBUR AS SalesOffice_VKBUR,
  vbak.GSBER AS BusinessAreaHdr_GSBER,
  vbak.GSKST AS CostCtrBusinessArea_GSKST,
  vbak.GUEBG AS AgreementValidFrom_GUEBG,
  vbak.GUEEN AS AgreementValidTo_GUEEN,
  vbak.KNUMV AS ConditionNumber_KNUMV,
  vbak.VDATU AS Requesteddeliverydate_VDATU,
  vbak.VPRGR AS Proposeddatetype_VPRGR,
  vbak.AUTLF AS CompleteDeliveryFlag_AUTLF,
  vbak.VBKLA AS OriginalSystem_VBKLA,
  vbak.VBKLT AS DocumentIndicator_VBKLT,
  vbak.KALSM AS PricingProcedure_KALSM,
  vbak.VSBED AS ShippingConditions_VSBED,
  vbak.FKARA AS Proposedbillingtype_FKARA,
  vbak.AWAHR AS Salesprobability_AWAHR,
  vbak.KTEXT AS Searchtermforproductproposal_KTEXT,
  vbak.BSTNK AS Customerpurchaseordernumber_BSTNK,
  vbak.BSARK AS Customerpurchaseordertype_BSARK,
  vbak.BSTDK AS Customerpurchaseorderdate_BSTDK,
  vbak.BSTZD AS Purchaseordernumbersupplement_BSTZD,
  vbak.IHREZ AS YourReference_IHREZ,
  vbak.BNAME AS Nameoforderer_BNAME,
  vbak.TELF1 AS TelephoneNumber_TELF1,
  vbak.MAHZA AS Numberofcontactsfromthecustomer_MAHZA,
  vbak.MAHDT AS Lastcustomercontactdate_MAHDT,
  vbak.KUNNR AS SoldtoParty_KUNNR,
  vbak.KOSTL AS CostCenterHdr_KOSTL,
  vbak.STAFO AS Updategroupforstatistics_STAFO,
  vbak.STWAE AS Statisticscurrency_STWAE,
  vbak.AEDAT AS ChangedOn_AEDAT,
  vbak.KVGR1 AS Customergroup1_KVGR1,
  vbak.KVGR2 AS Customergroup2_KVGR2,
  vbak.KVGR3 AS Customergroup3_KVGR3,
  vbak.KVGR4 AS Customergroup4_KVGR4,
  vbak.KVGR5 AS Customergroup5_KVGR5,
  vbak.KNUMA AS Agreement_KNUMA,
  vbak.KOKRS AS ControllingArea_KOKRS,
  vbak.PS_PSP_PNR AS WBSElementHdr_PS_PSP_PNR,
  vbak.KURST AS ExchangeRateType_KURST,
  vbak.KKBER AS Creditcontrolarea_KKBER,
  vbak.KNKLI AS CustomerCreditLimitRef_KNKLI,
  vbak.GRUPP AS CustomerCreditGroup_GRUPP,
  vbak.SBGRP AS Creditrepresentativegroupforcreditmanagement_SBGRP,
  vbak.CTLPC AS Riskcategory_CTLPC,
  vbak.CMWAE AS Currencykeyofcreditcontrolarea_CMWAE,
  vbak.CMFRE AS Releasedateofthedocumentdeterminedbycreditmanagement_CMFRE,
  vbak.CMNUP AS Dateofnextcreditcheckofdocument_CMNUP,
  vbak.CMNGV AS Nextdate_CMNGV,
  vbak.AMTBL AS Releasedcreditvalueofthedocument_AMTBL,
  vbak.HITYP_PR AS Hierarchytypeforpricing_HITYP_PR,
  vbak.ABRVW AS UsageIndicator_ABRVW,
  vbak.ABDIS AS MRPfordeliveryscheduletypes_ABDIS,
  vbak.VGBEL AS Documentnumberofthereferencedocument_VGBEL,
  vbak.OBJNR AS Objectnumberatheaderlevel_OBJNR,
  vbak.BUKRS_VF AS Companycodetobebilled_BUKRS_VF,
  vbak.TAXK1 AS Alternativetaxclassification_TAXK1,
  vbak.TAXK2 AS Taxclassification2_TAXK2,
  vbak.TAXK3 AS Taxclassification3_TAXK3,
  vbak.TAXK4 AS TaxClassification4_TAXK4,
  vbak.TAXK5 AS Taxclassification5_TAXK5,
  vbak.TAXK6 AS Taxclassification6_TAXK6,
  vbak.TAXK7 AS Taxclassification7_TAXK7,
  vbak.TAXK8 AS Taxclassification8_TAXK8,
  vbak.TAXK9 AS Taxclassification9_TAXK9,
  vbak.XBLNR AS ReferenceDocumentNumber_XBLNR,
  vbak.ZUONR AS Assignmentnumber_ZUONR,
  vbak.VGTYP AS PreDocCategory_VGTYP,
  vbak.AUFNR AS OrderNumberHdr_AUFNR,
  vbak.QMNUM AS NotificationNo_QMNUM,
  vbak.VBELN_GRP AS Mstercontractnumber_VBELN_GRP,
  vbak.STCEG_L AS TaxDestinationCountry_STCEG_L,
  vbak.LANDTX AS Taxdeparturecountry_LANDTX,
  vbak.HANDLE AS Internationaluniquekey_HANDLE,
  vbak.PROLI AS DangerousGoodsManagementProfile_PROLI,
  vbak.CONT_DG AS DangerousGoodsFlag_CONT_DG,
  vbak.UPD_TMSTMP AS UTCTimeStampL_UPD_TMSTMP,
  vbap.MATWA AS Materialentered_MATWA,
  vbap.PMATN AS PricingReferenceMaterial_PMATN,
  vbap.CHARG AS BatchNumber_CHARG,
  vbap.MATKL AS MaterialGroup_MATKL,
  vbap.ARKTX AS ShortText_ARKTX,
  vbap.PSTYV AS ItemCategory_PSTYV,
  vbap.POSAR AS ItemType_POSAR,
  vbap.LFREL AS RelevantforDelivery_LFREL,
  vbap.FKREL AS RelevantforBilling_FKREL,
  vbap.UEPOS AS BOMItemLevel_UEPOS,
  vbap.GRPOS AS AlternativeForItem_GRPOS,
  vbap.ABGRU AS RejectionReason_ABGRU,
  vbap.PRODH AS ProductHierarchy_PRODH,
  vbap.ZWERT AS TargetValue_ZWERT,
  vbap.ZMENG AS TargetQuantityUoM_ZMENG,
  vbap.ZIEME AS TargetquantityUoM_ZIEME,
  vbap.UMZIZ AS BaseTargetConversionFactor_UMZIZ,
  vbap.UMZIN AS ConversionFactor_UMZIN,
  vbap.MEINS AS BaseUnitofMeasure_MEINS,
  vbap.SMENG AS Scalequantity_SMENG,
  vbap.ABLFZ AS Roundingquantityfordelivery_ABLFZ,
  vbap.ABDAT AS ReconciliationDate_ABDAT,
  vbap.ABSFZ AS AllowedDeviation_ABSFZ,
  vbap.POSEX AS ItemNumberoftheUnderlyingPurchaseOrder_POSEX,
  vbap.KDMAT AS CustomerMaterialNumber_KDMAT,
  vbap.KBVER AS AlloweddeviationPercent_KBVER,
  vbap.KEVER AS Daysbywhichthequantitycanbeshifted_KEVER,
  vbap.VKGRU AS Repairprocessing_VKGRU,
  vbap.VKAUS AS UsageIndicator_VKAUS,
  vbap.GRKOR AS Deliverygroup_GRKOR,
  vbap.FMENG AS Quantityisfixed_FMENG,
  vbap.UEBTK AS Unlimitedoverdeliveryallowed_UEBTK,
  vbap.UEBTO AS OverdeliveryToleranceLimit_UEBTO,
  vbap.UNTTO AS UnderdeliveryToleranceLimit_UNTTO,
  vbap.FAKSP AS Billingblockforitem_FAKSP,
  vbap.ATPKZ AS Replacementpart_ATPKZ,
  vbap.RKFKF AS FormofBillingforCO_RKFKF,
  vbap.SPART AS Division_SPART,
  vbap.GSBER AS BusinessArea_GSBER,
  vbap.NETWR AS NetPrice_NETWR,
  vbap.WAERK AS Currency_WAERK,
  vbap.ANTLF AS MaximumPartialDeliveries_ANTLF,
  vbap.KZTLF AS Partialdeliveryatitemlevel_KZTLF,
  vbap.CHSPL AS Batchsplitallowed_CHSPL,
  vbap.KWMENG AS CumulativeOrderQuantity_KWMENG,
  vbap.LSMENG AS CumulativeTargetDeliveryQty_LSMENG,
  vbap.KBMENG AS CumulativeConfirmedQuantity_KBMENG,
  vbap.KLMENG AS CumulativeConfirmedQuantityinBaseUoM_KLMENG,
  vbap.VRKME AS Salesunit_VRKME,
  vbap.UMVKZ AS NumeratorQty_UMVKZ,
  vbap.UMVKN AS DenominatorQty_UMVKN,
  vbap.BRGEW AS Grossweightofitem_BRGEW,
  vbap.NTGEW AS Netweightofitem_NTGEW,
  vbap.GEWEI AS WeightUnit_GEWEI,
  vbap.VOLUM AS Volumeoftheitem_VOLUM,
  vbap.VOLEH AS Volumeunit_VOLEH,
  vbap.VBELV AS Originatingdocument_VBELV,
  vbap.POSNV AS Originatingitem_POSNV,
  vbap.VGBEL AS ReferenceDocument_VGBEL,
  vbap.VGPOS AS ReferenceItem_VGPOS,
  vbap.VOREF AS ReferenceIndicator_VOREF,
  vbap.UPFLU AS UpdateIndicator_UPFLU,
  vbap.ERLRE AS CompletionruleforQuotation_ERLRE,
  vbap.LPRIO AS DeliveryPriority_LPRIO,
  vbap.WERKS AS Plant_WERKS,
  vbap.LGORT AS StorageLocation_LGORT,
  vbap.VSTEL AS ShippingReceivingPoint_VSTEL,
  vbap.ROUTE AS Route_ROUTE,
  vbap.STKEY AS BOMOrigin_STKEY,
  vbap.STDAT AS BOMDate_STDAT,
  vbap.STLNR AS BOM_STLNR,
  vbap.AWAHR AS Orderprobabilityoftheitem_AWAHR,
  vbap.TAXM1 AS Taxclassification1_TAXM1,
  vbap.TAXM2 AS Taxclassification2_TAXM2,
  vbap.TAXM3 AS Taxclassification3_TAXM3,
  vbap.TAXM4 AS Taxclassification4_TAXM4,
  vbap.TAXM5 AS Taxclassification5_TAXM5,
  vbap.TAXM6 AS Taxclassification6_TAXM6,
  vbap.TAXM7 AS Taxclassification7_TAXM7,
  vbap.TAXM8 AS Taxclassification8_TAXM8,
  vbap.TAXM9 AS Taxclassification9_TAXM9,
  vbap.VBEAF AS Fixedshippingprocessingtimeindays_VBEAF,
  vbap.VBEAV AS Variableshippingprocessingtimeindays_VBEAV,
  vbap.VGREF AS Precedingdocumenthasresultedfromreference_VGREF,
  vbap.NETPR AS Netprice_NETPR,
  vbap.KPEIN AS Conditionpricingunit_KPEIN,
  vbap.KMEIN AS ConditionUnit_KMEIN,
  vbap.SHKZG AS ReturnsItem_SHKZG,
  vbap.SKTOF AS Cashdiscountindicator_SKTOF,
  vbap.MTVFP AS CheckingGroupforAvailabilityCheck_MTVFP,
  vbap.SUMBD AS Summingupofrequirements_SUMBD,
  vbap.KONDM AS MaterialPricingGroup_KONDM,
  vbap.KTGRM AS Accountassignmentgroupforthismaterial_KTGRM,
  vbap.BONUS AS Volumerebategroup_BONUS,
  vbap.PROVG AS Commissiongroup_PROVG,
  vbap.PRSOK AS PricingisOK_PRSOK,
  vbap.BWTAR AS Valuationtype_BWTAR,
  vbap.BWTEX AS Separatevaluation_BWTEX,
  vbap.XCHPF AS Batchmanagementrequirementindicator_XCHPF,
  vbap.XCHAR AS Batchmanagementindicator_XCHAR,
  vbap.LFMNG AS Minimumdeliveryquantityindeliverynoteprocessing_LFMNG,
  vbap.STAFO AS Updategroupforstatisticsupdate_STAFO,
  vbap.KZWI1 AS Subtotal1frompricingprocedureforcondition_KZWI1,
  vbap.KZWI2 AS Subtotal2frompricingprocedureforcondition_KZWI2,
  vbap.KZWI3 AS Subtotal3frompricingprocedureforcondition_KZWI3,
  vbap.KZWI4 AS Subtotal4frompricingprocedureforcondition_KZWI4,
  vbap.KZWI5 AS Subtotal5frompricingprocedureforcondition_KZWI5,
  vbap.KZWI6 AS Subtotal6frompricingprocedureforcondition_KZWI6,
  vbap.STCUR AS Exchangerateforstatistics_STCUR,
  vbap.AEDAT AS LastChangedOn_AEDAT,
  vbap.EAN11 AS InternationalArticleNumber_EAN11,
  vbap.FIXMG AS Deliverydateandquantityfixed_FIXMG,
  vbap.PRCTR AS ProfitCenter_PRCTR,
  vbap.MVGR1 AS Materialgroup1_MVGR1,
  vbap.MVGR2 AS Materialgroup2_MVGR2,
  vbap.MVGR3 AS Materialgroup3_MVGR3,
  vbap.MVGR4 AS Materialgroup4_MVGR4,
  vbap.MVGR5 AS Materialgroup5_MVGR5,
  vbap.KMPMG AS ComponentQuantity_KMPMG,
  vbap.SUGRD AS Reasonformaterialsubstitution_SUGRD,
  vbap.SOBKZ AS SpecialStockIndicator_SOBKZ,
  vbap.VPZUO AS AllocationIndicator_VPZUO,
  vbap.PAOBJNR AS ProfitabilitySegmentNumber_PAOBJNR,
  vbap.PS_PSP_PNR AS WBSElement_PS_PSP_PNR,
  vbap.AUFNR AS OrderNumber_AUFNR,
  vbap.VPMAT AS Planningmaterial_VPMAT,
  vbap.VPWRK AS Planningplant_VPWRK,
  vbap.PRBME AS Baseunitofmeasureforproductgroup_PRBME,
  vbap.UMREF AS Conversionfactorquantities_UMREF,
  vbap.KNTTP AS Accountassignmentcategory_KNTTP,
  vbap.KZVBR AS Consumptionposting_KZVBR,
  vbap.SERNR AS BOMexplosionnumber_SERNR,
  vbap.OBJNR AS Objectnumberatitemlevel_OBJNR,
  vbap.ABGRS AS ResultsAnalysisKey_ABGRS,
  vbap.BEDAE AS Requirementstype_BEDAE,
  vbap.CMPRE AS Itemcreditprice_CMPRE,
  vbap.CMTFG AS creditblock_CMTFG,
  vbap.CMPNT AS Relevantforcredit_CMPNT,
  vbap.CUOBJ AS Configuration_CUOBJ,
  vbap.CUOBJ_CH AS Internalobjectnumberofthebatchclassification_CUOBJ_CH,
  vbap.CEPOK AS Statusexpectedprice_CEPOK,
  vbap.KOUPD AS Conditionupdate_KOUPD,
  vbap.SERAIL AS SerialNumberProfile_SERAIL,
  vbap.ANZSN AS Numberofserialnumbers_ANZSN,
  vbap.NACHL AS Customerhasnotpostedgoodsreceipt_NACHL,
  vbap.MAGRV AS PackagingMaterials_MAGRV,
  vbap.MPROK AS Statusmanualpricechange_MPROK,
  vbap.VGTYP AS PrecedingDocCategory_VGTYP,
  vbap.KALNR AS CostEstimateNumber_KALNR,
  vbap.KLVAR AS CostingVariant_KLVAR,
  vbap.SPOSN AS BOMItemNumber_SPOSN,
  vbap.KOWRR AS Statisticalvalues_KOWRR,
  vbap.STADAT AS Statisticsdate_STADAT,
  vbap.EXART AS BusinessTransactionTypeforForeignTrade_EXART,
  vbap.PREFE AS ImportExportFlag_PREFE,
  vbap.KNUMH AS Numberofconditionrecord_KNUMH,
  vbap.CLINT AS InternalClassNumber_CLINT,
  vbap.STLTY AS BOMCategory_STLTY,
  vbap.STLKN AS BOMItemNodeNumber_STLKN,
  vbap.STPOZ AS Internalcounter_STPOZ,
  vbap.STMAN AS Inconsistentconfiguration_STMAN,
  vbap.ZSCHL_K AS Overheadkey_ZSCHL_K,
  vbap.KALSM_K AS CostingSheet_KALSM_K,
  vbap.KALVAR AS CostingVariant_KALVAR,
  vbap.KOSCH AS Productallocation_KOSCH,
  vbap.UPMAT AS PricingReferenceMaterial_UPMAT,
  vbap.UKONM AS MaterialPricingGroup_UKONM,
  vbap.MFRGR AS MaterialFreightGroup_MFRGR,
  vbap.PLAVO AS PlanningReleaseRegulation_PLAVO,
  vbap.KANNR AS KANBAN_KANNR,
  vbap.CMPRE_FLT AS Itemcreditprice_CMPRE_FLT,
  vbap.ABFOR AS Formofpaymentguarantee_ABFOR,
  vbap.ABGES AS GuaranteedFactor_ABGES,
  vbap.WKTNR AS Valuecontractno_WKTNR,
  vbap.WKTPS AS Valuecontractitem_WKTPS,
  vbap.SKOPF AS AssortmentModule_SKOPF,
  vbap.KZBWS AS ValuationofSpecialStock_KZBWS,
  vbap.WGRU1 AS Materialgrouphierarchy1_WGRU1,
  vbap.WGRU2 AS Materialgrouphierarchy2_WGRU2,
  vbap.KNUMA_PI AS Promotion_KNUMA_PI,
  vbap.KNUMA_AG AS Salesdeal_KNUMA_AG,
  vbap.KZFME AS LeadingUoM_KZFME,
  vbap.LSTANR AS FreegoodsDeliveryControl_LSTANR,
  vbap.TECHS AS ParameterVariant_TECHS,
  vbap.BERID AS MRPArea_BERID,
  vbap.PCTRF AS ProfitCenterforBilling_PCTRF,
  vbap.STOCKLOC AS ManagingLocation_STOCKLOC,
  vbap.SLOCTYPE AS TypeofFirstInventory_SLOCTYPE,
  vbap.MSR_RET_REASON AS ReturnReason_MSR_RET_REASON,
  vbap.MSR_REFUND_CODE AS ReturnsRefundCode_MSR_REFUND_CODE,
  vbap.MSR_APPROV_BLOCK AS ApprovalBlock_MSR_APPROV_BLOCK,
  vbap.NRAB_KNUMH AS Conditionrecordnumber_NRAB_KNUMH,
  vbap.TRMRISK_RELEVANT AS RiskRelevancyinSales_TRMRISK_RELEVANT,
  vbap.HANDOVERLOC AS Locationforaphysicalhandoverofgoods_HANDOVERLOC,
  vbap.HANDOVERDATE AS HandoverDateattheHandoverLocation_HANDOVERDATE,
  vbap.HANDOVERTIME AS Handovertimeatthehandoverlocation_HANDOVERTIME,
  vbap.TC_AUT_DET AS TaxCodeAutomaticallyDetermined_TC_AUT_DET,
  vbap.MANUAL_TC_REASON AS ManualTaxCodeReason_MANUAL_TC_REASON,
  vbap.FISCAL_INCENTIVE AS TaxIncentiveType_FISCAL_INCENTIVE,
  vbap.FISCAL_INCENTIVE_ID AS IncentiveID_FISCAL_INCENTIVE_ID,
  vbap.SPCSTO AS NotaFiscalSpecialCaseforCFOPDetermination_SPCSTO,
  vbap.KOSTL AS CostCenter_KOSTL,
  vbap.FONDS AS Fund_FONDS,
  vbap.FISTL AS FundsCenter_FISTL,
  vbap.FKBER AS FunctionalArea_FKBER,
  COALESCE(vbak.NETWR * tcurx_vbak.CURRFIX, vbak.NETWR) AS NetValueoftheSalesOrderinDocumentCurrency_NETWR,
  COALESCE(vbak.NETWR * tcurx_vbak.CURRFIX, vbak.NETWR) * conv_vbak.UKURS AS NetValueoftheSalesOrderinDocumentCurrencyUSD_NETWR,
  COALESCE(vbap.WAVWR * tcurx_vbap.CURRFIX, vbap.WAVWR) AS Costindocumentcurrency_WAVWR,
  COALESCE(vbap.WAVWR * tcurx_vbap.CURRFIX, vbap.WAVWR) * conv_vbap.UKURS AS CostindocumentcurrencyUSD_WAVWR,
  COALESCE(vbap.MWSBP * tcurx_vbap.CURRFIX, vbap.MWSBP) AS Taxamountindocumentcurrency_MWSBP,
  COALESCE(vbap.MWSBP * tcurx_vbap.CURRFIX, vbap.MWSBP) * conv_vbap.UKURS AS Taxamountindocumentcurrencyusd_MWSBP
FROM `{{ project_id_src }}.{{ dataset_cdc_processed }}.vbak` AS vbak
INNER JOIN `{{ project_id_src }}.{{ dataset_cdc_processed }}.vbap` AS vbap
  ON vbak.vbeln = vbap.vbeln
    AND vbak.mandt = vbap.mandt
LEFT JOIN TCURX AS tcurx_vbak
  ON vbak.WAERK = tcurx_vbak.CURRKEY
LEFT JOIN TCURX AS tcurx_vbap
  ON vbap.WAERK = tcurx_vbap.CURRKEY
LEFT JOIN CONV AS conv_vbak
  ON vbak.MANDT = conv_vbak.MANDT
    AND vbak.WAERK = conv_vbak.FCURR
    AND vbak.ERDAT = conv_vbak.GDATU
LEFT JOIN CONV AS conv_vbap
  ON vbap.MANDT = conv_vbap.MANDT
    AND vbap.WAERK = conv_vbap.FCURR
    AND vbap.ERDAT = conv_vbap.GDATU
